import Icon from '../../components/Icon'
import NaviPrompt from '../../components/user/NaviPrompt'
import SectionHead from '../../components/user/SectionHead'
import { useState } from 'react'
import { careers } from '../../data'

export default function CareerDetailPage({ navigate, careerId = 'ux-designer' }) {
  const career = careers.find((item) => item.id === careerId) || careers[0]
  const [saved, setSaved] = useState(false)
  return (
    <div className="career-detail page-stack">
      <button className="back-link" onClick={() => navigate('careers')}><Icon name="arrowLeft" /> Back to Career Bank</button>
      <section className="career-detail-hero"><div className="career-title-block"><span className={`career-icon xl ${career.tone}`}><Icon name={career.icon} size={30} /></span><div><span className="match-pill"><Icon name="sparkles" size={13} /> {career.match}% match for you</span><h1>{career.title}</h1><p>{career.field} · Updated August 2026</p></div></div><div className="detail-actions"><button className={`button soft ${saved ? 'saved' : ''}`} onClick={() => setSaved(!saved)}><Icon name="bookmark" /> {saved ? 'Saved' : 'Save career'}</button><button className="button primary" onClick={() => navigate('quiz')}>Add to my roadmap <Icon name="plus" /></button></div></section>
      <div className="detail-layout"><div className="detail-main"><section className="panel prose-card"><span className="eyebrow">Career snapshot</span><h2>Design experiences that make technology feel simple.</h2><p>{career.summary} UX designers work closely with users, product managers, and engineers to research needs, test ideas, and refine every interaction.</p><div className="snapshot-grid"><div><span className="snapshot-icon"><Icon name="briefcase" /></span><small>Typical salary</small><strong>{career.salary}</strong><p>US national range</p></div><div><span className="snapshot-icon"><Icon name="trend" /></span><small>Projected growth</small><strong>{career.growth}</strong><p>Over the next 10 years</p></div><div><span className="snapshot-icon"><Icon name="clock" /></span><small>Time to job-ready</small><strong>6–12 months</strong><p>With focused learning</p></div></div></section>
        <section className="panel"><SectionHead eyebrow="A day in the work" title={`What ${career.title}s actually do`} /><div className="responsibility-list"><div><span>01</span><p><strong>Understand the real problem</strong><small>Interview people, observe behavior, and turn messy needs into clear opportunities.</small></p></div><div><span>02</span><p><strong>Explore and prototype ideas</strong><small>Sketch flows and build testable prototypes before expensive development begins.</small></p></div><div><span>03</span><p><strong>Collaborate and improve</strong><small>Partner across a team, use feedback, and refine details until the experience feels right.</small></p></div></div></section>
        <section className="panel"><SectionHead eyebrow="Skills map" title="What you’ll need to thrive" /><div className="skills-map"><div><strong>Core skills</strong>{career.skills.map((skill, i) => <div key={skill}><span>{skill}</span><div><i style={{ width: `${88 - i * 9}%` }} /></div><small>{88 - i * 9}%</small></div>)}</div><div><strong>Tools to learn</strong><div className="tool-grid"><span>Fi<strong>Figma</strong></span><span>Mi<strong>Miro</strong></span><span>Nt<strong>Notion</strong></span><span>Ma<strong>Maze</strong></span></div></div></div></section>
        <section className="panel roadmap"><SectionHead eyebrow="Your personalized route" title="A practical path into this career" /><div className="roadmap-line"><div className="done"><span><Icon name="check" /></span><p><small>Step 1 · Complete</small><strong>Understand the foundations</strong><em>2 weeks</em></p></div><div className="current"><span>2</span><p><small>Step 2 · Your next move</small><strong>Practice research and prototyping</strong><em>6–8 weeks</em></p><button>View learning plan</button></div><div><span>3</span><p><small>Step 3</small><strong>Build two portfolio projects</strong><em>8–12 weeks</em></p></div><div><span>4</span><p><small>Step 4</small><strong>Prepare and start applying</strong><em>4 weeks</em></p></div></div></section></div>
        <aside className="detail-aside"><NaviPrompt pose="explaining" title="Why this fits you">Your empathy helps you notice what people need, while your analytical side enjoys turning that insight into a clear system.</NaviPrompt><div className="panel fit-card"><span className="eyebrow">Your fit</span><div className="fit-score"><strong>{career.match}%</strong><div><span style={{ width: `${career.match}%` }} /></div></div><ul><li><Icon name="check" /> Strong interest alignment</li><li><Icon name="check" /> Natural skill overlap</li><li><Icon name="check" /> Matches your work style</li></ul><button onClick={() => navigate('recommendations')}>Compare with other matches</button></div><div className="panel expert-card"><div className="expert-video"><span><Icon name="play" /></span><small>08:14</small></div><span className="eyebrow">Expert story</span><h3>“What I wish I knew before UX”</h3><p>Maya Chen · Senior Product Designer</p><button>Watch story <Icon name="arrow" /></button></div></aside></div>
    </div>
  )
}
