import Icon from '../../components/Icon'
import PageTitle from '../../components/common/PageTitle'
import { useState } from 'react'
import { frontendFixtures } from '../../services/pathseekerApi'

export default function SavedFiltersPage({ navigate }) {
  const [filters, setFilters] = useState(frontendFixtures.savedFilters)
  const [editing, setEditing] = useState(null)
  return <div className="page-stack"><PageTitle eyebrow="Career Bank" title="Saved searches and filters" copy="Return to useful searches quickly and optionally receive alerts when new careers match." actions={<button className="button primary" onClick={() => setEditing({ _id: 'new', name: '', domains: ['Design'], salaryMin: 50000, demand: 'Any', alerts: false })}><Icon name="plus" /> New saved filter</button>} /><section className="saved-filter-grid">{filters.map((filter) => <article className="panel" key={filter._id}><div><span className="filter-icon"><Icon name="filter" /></span><button><Icon name="more" /></button></div><h3>{filter.name}</h3><p>{filter.domains.join(' + ')} · ${filter.salaryMin.toLocaleString()}+ · {filter.demand} demand</p><span className={`alert-pill ${filter.alerts ? 'on' : ''}`}><Icon name="bell" /> Alerts {filter.alerts ? 'on' : 'off'}</span><div><button className="button soft small" onClick={() => navigate('careers')}>Apply filter</button><button className="button ghost small" onClick={() => setEditing(filter)}>Edit</button></div></article>)}</section>{editing && <div className="inline-editor panel"><div><span className="eyebrow">{editing._id === 'new' ? 'New filter' : 'Edit filter'}</span><h2>Filter preferences</h2></div><form onSubmit={(event) => { event.preventDefault(); if (editing._id === 'new') setFilters([...filters, { ...editing, _id: `filter_0${filters.length + 1}`, name: editing.name || 'My saved search' }]); else setFilters(filters.map((filter) => filter._id === editing._id ? editing : filter)); setEditing(null) }}><label>Filter name<input value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><label>Minimum salary<input type="number" value={editing.salaryMin} onChange={(event) => setEditing({ ...editing, salaryMin: Number(event.target.value) })} /></label><label>Demand<select value={editing.demand} onChange={(event) => setEditing({ ...editing, demand: event.target.value })}><option>Any</option><option>High</option><option>Very high</option></select></label><label className="check-row"><input type="checkbox" checked={editing.alerts} onChange={(event) => setEditing({ ...editing, alerts: event.target.checked })} /> Email me when new careers match</label><div><button className="button ghost" type="button" onClick={() => setEditing(null)}>Cancel</button><button className="button primary" type="submit">Save filter</button></div></form></div>}</div>
}
