import Icon from '../../components/Icon'
import Back from '../../components/common/BackButton'
import { useState } from 'react'
import { resources } from '../../data'

export default function MediaDetailPage({ navigate }) {
  const [playing, setPlaying] = useState(false)
  const [transcript, setTranscript] = useState(true)
  const [rating, setRating] = useState(4)
  return <div className="page-stack"><Back navigate={navigate} to="resources">Back to resources</Back><div className="media-layout"><main><section className="media-player"><div className="media-stage"><span className="career-icon blue"><Icon name="chart" size={38} /></span><div><small>Expert story</small><strong>A day in the life of a data analyst</strong></div><button className="media-play" onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pause' : 'Play'}><Icon name={playing ? 'pause' : 'play'} size={32} /></button></div><div className="media-controls"><button onClick={() => setPlaying(!playing)}><Icon name={playing ? 'pause' : 'play'} /></button><span>03:18</span><div><i style={{ width: '28%' }} /></div><span>12:04</span><button>1×</button><button><Icon name="more" /></button></div></section><section className="media-copy"><span className="eyebrow">Video · Data & business</span><h1>A day in the life of a data analyst</h1><p>Follow Sam through a real project—from cleaning messy information to presenting one clear recommendation.</p><div className="teacher"><span>SW</span><p><strong>Sam Wilson</strong><small>Senior Data Analyst · Northstar</small></p></div></section><section className="panel transcript-card"><div><div><span className="eyebrow">Accessibility</span><h2>Transcript</h2></div><button className="button soft small" onClick={() => setTranscript(!transcript)}>{transcript ? 'Hide' : 'Show'} transcript</button></div>{transcript && <div className="transcript-lines"><p><time>00:00</time><span><strong>Sam:</strong> Most days start with a question, not a spreadsheet. Today our product team wants to understand why new users stop during setup.</span></p><p className="active"><time>03:18</time><span><strong>Sam:</strong> Cleaning data is less glamorous than the chart, but it is where careful thinking matters most.</span></p><p><time>05:46</time><span><strong>Sam:</strong> The goal is not to show everything you found. It is to help someone make a better decision.</span></p></div>}</section></main><aside><section className="panel rating-card"><span className="eyebrow">Was this useful?</span><h3>Rate this resource</h3><div>{[1,2,3,4,5].map((star) => <button className={star <= rating ? 'active' : ''} key={star} onClick={() => setRating(star)}><Icon name="star" /></button>)}</div><small>Your rating helps improve recommendations.</small></section><section className="panel related-card"><span className="eyebrow">Up next</span><h3>Related resources</h3>{resources.slice(0, 3).map((resource) => <button key={resource.title}><span className={`resource-icon ${resource.tone}`}><Icon name={resource.icon} /></span><span><strong>{resource.title}</strong><small>{resource.meta}</small></span><Icon name="arrow" /></button>)}</section></aside></div></div>
}
