import Icon from '../../components/Icon'
import SectionHead from '../../components/user/SectionHead'
import CareerCard from '../../components/user/CareerCard'
import { useState } from 'react'
import { careers, resources } from '../../data'

export default function SavedPage({ navigate }) {
  const [tab, setTab] = useState('Careers')
  return (
    <div className="saved-page page-stack"><section className="page-intro"><div><span className="eyebrow">Your collection</span><h1>Saved ideas & notes</h1><p>Everything you want to revisit, organized in one calm place.</p></div><button className="button primary"><Icon name="plus" /> New note</button></section><div className="tab-row"><button className={tab === 'Careers' ? 'active' : ''} onClick={() => setTab('Careers')}>Saved careers <span>3</span></button><button className={tab === 'Resources' ? 'active' : ''} onClick={() => setTab('Resources')}>Resources <span>4</span></button><button className={tab === 'Notes' ? 'active' : ''} onClick={() => setTab('Notes')}>My notes <span>5</span></button></div>{tab === 'Careers' && <div className="saved-layout"><section><div className="career-grid two-col">{careers.slice(0, 3).map((career) => <CareerCard key={career.id} career={career} navigate={navigate} saved toggleSaved={() => {}} compact />)}</div></section><aside className="panel notes-preview"><SectionHead eyebrow="Related notes" title="Thoughts to revisit" link="See all" /><article><span className="note-dot mint" /><div><strong>Portfolio ideas</strong><p>Redesign the campus event sign-up flow and test it with five students…</p><small>UX Designer · 2 days ago</small></div></article><article><span className="note-dot blue" /><div><strong>Questions for Sam</strong><p>Ask what a junior analyst really does during their first 90 days.</p><small>Data Analyst · Aug 18</small></div></article><button className="new-note"><Icon name="plus" /> Add a note</button></aside></div>}{tab === 'Resources' && <div className="resource-grid">{resources.slice(0, 4).map((resource) => <article key={resource.title} className="resource-card"><div className={`resource-cover ${resource.tone}`}><Icon name={resource.icon} size={32} /><span>{resource.type}</span></div><div><span className="resource-type">{resource.type}</span><h3>{resource.title}</h3><p>{resource.meta}</p></div></article>)}</div>}{tab === 'Notes' && <div className="notes-grid">{['Portfolio ideas', 'Questions for Sam', 'What energizes me', 'Data skills to practice', 'Questions for Navi'].map((title, i) => <article key={title} className="panel"><div><span className={`note-dot ${['mint','blue','lavender','amber','rose'][i]}`} /><button><Icon name="more" /></button></div><h3>{title}</h3><p>{['Redesign the campus event sign-up flow and test it with five students.', 'Ask what a junior analyst really does during their first 90 days.', 'Facilitating workshops, visual problem solving, and making complex ideas clear.', 'SQL joins, dashboard design, and presenting a recommendation with confidence.', 'How do I choose between two careers that fit different sides of me?'][i]}</p><small>Edited {i + 1} days ago</small></article>)}</div>}</div>
  )
}
