import { careerIds, domainIds, skillIds } from './ids.js'

const BLS = 'U.S. Bureau of Labor Statistics, Occupational Outlook Handbook'
const publishedAt = new Date('2026-08-01T00:00:00.000Z')

const source = (occupationLabel, url) => ({
  name: BLS,
  occupationLabel,
  url,
  geography: 'United States',
  salaryYear: 2024,
  outlookPeriod: '2024-2034',
})

const rawCareersSeed = [
  {
    _id: careerIds.uxDesigner,
    slug: 'ux-ui-designer',
    title: 'UX/UI Designer',
    domainId: domainIds.design,
    summary: 'Research, design, and test digital experiences that people can use with confidence.',
    description: 'UX/UI designers study user needs, organize information, prototype interfaces, and test whether digital products are understandable and accessible. Titles vary across product design, interaction design, and UX research.',
    educationPath: 'Common routes include a design, human-computer interaction, psychology, or computing degree; a focused certificate; or a portfolio-led transition. Employers usually expect case studies that show research, decisions, accessibility, and iteration.',
    requiredSkillIds: [skillIds.uxResearch, skillIds.uiDesign, skillIds.prototyping, skillIds.empathy, skillIds.presentation],
    responsibilities: ['Plan interviews and usability tests.', 'Turn findings into flows, wireframes, and prototypes.', 'Collaborate with product and engineering teams.', 'Check accessibility and validate changes with users.'],
    toolsToLearn: ['Figma', 'FigJam or Miro', 'Maze or moderated testing', 'Accessibility inspection tools'],
    traits: ['creative', 'empathy', 'communication'],
    salaryMin: 60_000, salaryMax: 145_000, salaryMedian: 98_090, salaryCurrency: 'USD', demand: 'high', growthPercent: 7,
    timeToJobReadyMinMonths: 6, timeToJobReadyMaxMonths: 15, icon: 'pen', tone: 'lavender',
    tags: ['design', 'ux', 'ui', 'product design', 'user research', 'accessibility'],
    dataSource: source('Web and digital interface designers', 'https://www.bls.gov/ooh/computer-and-information-technology/web-developers.htm'),
  },
  {
    _id: careerIds.dataAnalyst,
    slug: 'data-analyst',
    title: 'Data Analyst',
    domainId: domainIds.dataAi,
    summary: 'Turn messy information into trustworthy evidence for decisions.',
    description: 'Data analysts clean and combine data, define metrics, explore patterns, and communicate findings through reports and dashboards. The role may be called business intelligence analyst, reporting analyst, or operations analyst.',
    educationPath: 'Entry routes include degrees in analytics, business, economics, mathematics, or computing, and portfolio-led transitions supported by spreadsheet, SQL, visualization, and statistics projects.',
    requiredSkillIds: [skillIds.dataAnalysis, skillIds.sql, skillIds.dataVisualization, skillIds.statistics, skillIds.presentation],
    responsibilities: ['Profile and clean source data.', 'Write SQL queries and validate results.', 'Build reports and dashboards for a defined audience.', 'Explain findings, uncertainty, and limitations.'],
    toolsToLearn: ['Excel or Google Sheets', 'SQL', 'Power BI or Tableau', 'Python (role dependent)'],
    traits: ['analytical', 'technical', 'communication'],
    salaryMin: 55_000, salaryMax: 135_000, salaryMedian: 91_290, salaryCurrency: 'USD', demand: 'very_high', growthPercent: 21,
    timeToJobReadyMinMonths: 4, timeToJobReadyMaxMonths: 10, icon: 'chart', tone: 'blue',
    tags: ['data', 'analytics', 'sql', 'business intelligence', 'visualization'],
    dataSource: source('Operations research analysts (closest BLS comparison)', 'https://www.bls.gov/ooh/math/operations-research-analysts.htm'),
  },
  {
    _id: careerIds.dataScientist,
    slug: 'data-scientist',
    title: 'Data Scientist',
    domainId: domainIds.dataAi,
    summary: 'Use statistics, code, and domain knowledge to model complex questions.',
    description: 'Data scientists acquire and analyze large datasets, build statistical or machine-learning models, evaluate performance, and help organizations use data responsibly. The work requires strong problem framing as well as coding.',
    educationPath: 'A bachelor degree in mathematics, statistics, computing, engineering, or a related field is common. Some employers prefer a masters or doctorate. Strong projects should show validation, communication, and responsible model use.',
    requiredSkillIds: [skillIds.python, skillIds.statistics, skillIds.machineLearning, skillIds.dataAnalysis, skillIds.communication],
    responsibilities: ['Frame questions that data can answer.', 'Prepare data and engineer useful features.', 'Build and evaluate models against a baseline.', 'Communicate uncertainty, risks, and practical recommendations.'],
    toolsToLearn: ['Python', 'pandas and scikit-learn', 'SQL', 'Jupyter', 'Git'],
    traits: ['analytical', 'technical', 'research'],
    salaryMin: 65_000, salaryMax: 195_000, salaryMedian: 112_590, salaryCurrency: 'USD', demand: 'very_high', growthPercent: 34,
    timeToJobReadyMinMonths: 12, timeToJobReadyMaxMonths: 30, icon: 'sparkles', tone: 'lavender',
    tags: ['data science', 'machine learning', 'python', 'statistics', 'ai'],
    dataSource: source('Data scientists', 'https://www.bls.gov/ooh/math/data-scientists.htm'),
  },
  {
    _id: careerIds.softwareEngineer,
    slug: 'software-engineer',
    title: 'Software Engineer',
    domainId: domainIds.softwareEngineering,
    summary: 'Design, build, test, and maintain software used by people and organizations.',
    description: 'Software engineers turn requirements into reliable applications and systems. They model data, write and review code, test behavior, investigate failures, and collaborate across product, design, security, and operations.',
    educationPath: 'A computing or engineering degree is common, but apprenticeships and strong portfolio-led routes also exist. Entry candidates should be able to build, test, document, and explain at least one complete application.',
    requiredSkillIds: [skillIds.javascript, skillIds.apiDesign, skillIds.problemSolving, skillIds.softwareTesting, skillIds.teamwork],
    responsibilities: ['Design and implement software features.', 'Write automated tests and review code.', 'Diagnose defects and improve reliability.', 'Document technical decisions and collaborate with stakeholders.'],
    toolsToLearn: ['Git', 'A programming language', 'Testing frameworks', 'Databases', 'Cloud deployment basics'],
    traits: ['technical', 'analytical', 'teamwork'],
    salaryMin: 80_000, salaryMax: 210_000, salaryMedian: 133_080, salaryCurrency: 'USD', demand: 'very_high', growthPercent: 16,
    timeToJobReadyMinMonths: 6, timeToJobReadyMaxMonths: 18, icon: 'code', tone: 'mint',
    tags: ['engineering', 'software', 'developer', 'programming', 'web development'],
    dataSource: source('Software developers', 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm'),
  },
  {
    _id: careerIds.qaEngineer,
    slug: 'software-qa-engineer',
    title: 'Software QA Engineer',
    domainId: domainIds.softwareEngineering,
    summary: 'Protect product quality by finding risks before users do.',
    description: 'Software quality assurance engineers analyze requirements, design test strategies, automate repeatable checks, investigate defects, and help teams prevent failures across the delivery lifecycle.',
    educationPath: 'Common routes include computing degrees, testing certificates, support-to-QA transitions, and portfolios that demonstrate risk-based test design, API testing, accessibility, and automation.',
    requiredSkillIds: [skillIds.softwareTesting, skillIds.testAutomation, skillIds.problemSolving, skillIds.apiDesign, skillIds.communication],
    responsibilities: ['Turn requirements into risk-focused test scenarios.', 'Automate stable regression checks.', 'Investigate, document, and reproduce defects.', 'Partner with developers and designers to prevent quality issues.'],
    toolsToLearn: ['Playwright or Cypress', 'Postman', 'GitHub Actions', 'Browser developer tools'],
    traits: ['analytical', 'technical', 'organization'],
    salaryMin: 60_000, salaryMax: 150_000, salaryMedian: 102_610, salaryCurrency: 'USD', demand: 'high', growthPercent: 10,
    timeToJobReadyMinMonths: 4, timeToJobReadyMaxMonths: 10, icon: 'check', tone: 'blue',
    tags: ['quality assurance', 'software testing', 'automation', 'qa', 'accessibility'],
    dataSource: source('Software quality assurance analysts and testers', 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm'),
  },
  {
    _id: careerIds.cloudEngineer,
    slug: 'cloud-engineer',
    title: 'Cloud Engineer',
    domainId: domainIds.softwareEngineering,
    summary: 'Build secure, observable infrastructure for applications and teams.',
    description: 'Cloud engineers provision infrastructure, automate delivery, monitor systems, improve reliability, and help development teams run services safely at scale. Titles overlap with platform, DevOps, and site reliability engineering.',
    educationPath: 'Computing degrees are common, but IT support, networking, and software backgrounds can transition through hands-on labs and certifications. Employers value demonstrable automation, Linux, networking, and security practice.',
    requiredSkillIds: [skillIds.cloudInfrastructure, skillIds.devOps, skillIds.networkSecurity, skillIds.apiDesign, skillIds.problemSolving],
    responsibilities: ['Provision repeatable cloud infrastructure.', 'Build CI/CD and operational automation.', 'Monitor availability, cost, and security.', 'Respond to incidents and document recovery.'],
    toolsToLearn: ['AWS, Azure, or Google Cloud', 'Linux', 'Docker', 'Terraform', 'GitHub Actions'],
    traits: ['technical', 'analytical', 'organization'],
    salaryMin: 80_000, salaryMax: 200_000, salaryMedian: 133_080, salaryCurrency: 'USD', demand: 'very_high', growthPercent: 16,
    timeToJobReadyMinMonths: 9, timeToJobReadyMaxMonths: 20, icon: 'globe', tone: 'navy',
    tags: ['cloud', 'devops', 'platform engineering', 'infrastructure', 'reliability'],
    dataSource: source('Software developers (BLS proxy for cloud software engineering)', 'https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm'),
  },
  {
    _id: careerIds.digitalMarketer,
    slug: 'digital-marketing-specialist',
    title: 'Digital Marketing Specialist',
    domainId: domainIds.marketing,
    summary: 'Connect products with audiences through measurable digital campaigns.',
    description: 'Digital marketing specialists research audiences, plan content and campaigns, manage search or social channels, and analyze performance. Strong practitioners connect creative work to a clear customer and business objective.',
    educationPath: 'Marketing, communications, or business degrees are common, but project portfolios and platform certificates can support entry. Candidates should show campaign thinking, ethical data use, copy, experimentation, and reporting.',
    requiredSkillIds: [skillIds.digitalMarketing, skillIds.seo, skillIds.contentStrategy, skillIds.dataAnalysis, skillIds.communication],
    responsibilities: ['Research customer needs and channel behavior.', 'Plan and publish campaigns.', 'Measure acquisition, engagement, and conversion.', 'Run experiments and communicate recommendations.'],
    toolsToLearn: ['Google Analytics', 'Google Ads', 'Email platforms', 'SEO research tools', 'Spreadsheets'],
    traits: ['creative', 'communication', 'analytical'],
    salaryMin: 45_000, salaryMax: 125_000, salaryMedian: 76_950, salaryCurrency: 'USD', demand: 'high', growthPercent: 7,
    timeToJobReadyMinMonths: 3, timeToJobReadyMaxMonths: 9, icon: 'megaphone', tone: 'amber',
    tags: ['marketing', 'seo', 'content', 'social media', 'ecommerce'],
    dataSource: source('Market research analysts and marketing specialists', 'https://www.bls.gov/ooh/business-and-financial/market-research-analysts.htm'),
  },
  {
    _id: careerIds.cybersecurityAnalyst,
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    domainId: domainIds.cybersecurity,
    summary: 'Reduce security risk by monitoring systems, investigating incidents, and strengthening controls.',
    description: 'Cybersecurity analysts protect networks, devices, applications, and information. They assess risk, monitor events, investigate suspicious activity, communicate incidents, and improve controls with legal and ethical care.',
    educationPath: 'A computing or cybersecurity degree is common, and employers may prefer relevant experience or certification. IT support and networking can be practical starting points. Build legal labs and never test systems without permission.',
    requiredSkillIds: [skillIds.cybersecurity, skillIds.networkSecurity, skillIds.riskManagement, skillIds.criticalThinking, skillIds.communication],
    responsibilities: ['Monitor and triage security events.', 'Investigate incidents and preserve useful evidence.', 'Assess vulnerabilities and recommend controls.', 'Explain risk and response decisions to stakeholders.'],
    toolsToLearn: ['Linux', 'Wireshark', 'SIEM platforms', 'Nmap in authorized labs', 'Python basics'],
    traits: ['technical', 'analytical', 'ethics'],
    salaryMin: 70_000, salaryMax: 185_000, salaryMedian: 124_910, salaryCurrency: 'USD', demand: 'very_high', growthPercent: 29,
    timeToJobReadyMinMonths: 6, timeToJobReadyMaxMonths: 18, icon: 'shield', tone: 'rose',
    tags: ['cybersecurity', 'security', 'network', 'infosec', 'risk'],
    dataSource: source('Information security analysts', 'https://www.bls.gov/ooh/computer-and-information-technology/information-security-analysts.htm'),
  },
  {
    _id: careerIds.productManager,
    slug: 'product-manager',
    title: 'Product Manager',
    domainId: domainIds.business,
    summary: 'Align customer evidence, business goals, and delivery teams around valuable outcomes.',
    description: 'Product managers clarify problems, shape strategy, prioritize opportunities, and help cross-functional teams learn whether solutions create value. The role varies widely by organization and is not generally an entry-level title.',
    educationPath: 'People enter from business, design, engineering, analytics, operations, and customer-facing roles. Strong evidence includes shipped work, discovery, prioritization, stakeholder alignment, and measured outcomes.',
    requiredSkillIds: [skillIds.productStrategy, skillIds.uxResearch, skillIds.dataAnalysis, skillIds.stakeholderManagement, skillIds.communication],
    responsibilities: ['Research customer and business problems.', 'Define outcomes and prioritize opportunities.', 'Align design, engineering, and stakeholders.', 'Measure results and adapt the roadmap.'],
    toolsToLearn: ['Product analytics', 'Roadmapping tools', 'Figma basics', 'SQL basics', 'Experiment documentation'],
    traits: ['people', 'communication', 'analytical'],
    salaryMin: 70_000, salaryMax: 175_000, salaryMedian: 101_190, salaryCurrency: 'USD', demand: 'high', growthPercent: 9,
    timeToJobReadyMinMonths: 12, timeToJobReadyMaxMonths: 30, icon: 'target', tone: 'mint',
    tags: ['product', 'management', 'strategy', 'leadership', 'discovery'],
    dataSource: source('Management analysts (BLS proxy)', 'https://www.bls.gov/ooh/business-and-financial/management-analysts.htm'),
  },
  {
    _id: careerIds.projectManager,
    slug: 'project-management-specialist',
    title: 'Project Management Specialist',
    domainId: domainIds.business,
    summary: 'Coordinate scope, schedule, people, cost, and risk so important work can finish well.',
    description: 'Project management specialists develop plans, coordinate contributors and vendors, track milestones and budgets, communicate risk, resolve delivery problems, and close projects with useful documentation.',
    educationPath: 'A bachelor degree in business, project management, or the project domain is common. Certifications can help but do not replace delivery evidence. Coordinating student, volunteer, or operational projects can build entry experience.',
    requiredSkillIds: [skillIds.projectManagement, skillIds.criticalThinking, skillIds.riskManagement, skillIds.stakeholderManagement, skillIds.communication],
    responsibilities: ['Clarify scope, objectives, deliverables, and constraints.', 'Build and maintain a practical plan.', 'Track risks, costs, dependencies, and milestones.', 'Coordinate communication and project closure.'],
    toolsToLearn: ['Jira or Trello', 'Spreadsheets', 'Risk registers', 'Project schedules', 'Meeting documentation'],
    traits: ['organization', 'communication', 'leadership'],
    salaryMin: 55_000, salaryMax: 160_000, salaryMedian: 100_750, salaryCurrency: 'USD', demand: 'high', growthPercent: 6,
    timeToJobReadyMinMonths: 5, timeToJobReadyMaxMonths: 15, icon: 'calendar', tone: 'blue',
    tags: ['project management', 'delivery', 'operations', 'planning', 'stakeholders'],
    dataSource: source('Project management specialists', 'https://www.bls.gov/ooh/business-and-financial/project-management-specialists.htm'),
  },
  {
    _id: careerIds.businessAnalyst,
    slug: 'business-analyst',
    title: 'Business Analyst',
    domainId: domainIds.business,
    summary: 'Understand processes and requirements, then help teams make practical improvements.',
    description: 'Business analysts investigate how work happens, identify needs and constraints, model processes, clarify requirements, and evaluate options. The role connects stakeholders with delivery or operational teams.',
    educationPath: 'Business, information systems, economics, and computing degrees are common. People also transition from operations, support, finance, or domain roles by demonstrating process analysis and stakeholder communication.',
    requiredSkillIds: [skillIds.businessAnalysis, skillIds.research, skillIds.dataAnalysis, skillIds.stakeholderManagement, skillIds.presentation],
    responsibilities: ['Interview stakeholders and observe processes.', 'Map current and future workflows.', 'Document testable requirements and acceptance criteria.', 'Evaluate options, outcomes, and operational impact.'],
    toolsToLearn: ['Process mapping tools', 'Spreadsheets', 'SQL basics', 'Jira', 'Presentation tools'],
    traits: ['analytical', 'communication', 'organization'],
    salaryMin: 60_000, salaryMax: 155_000, salaryMedian: 101_190, salaryCurrency: 'USD', demand: 'high', growthPercent: 9,
    timeToJobReadyMinMonths: 4, timeToJobReadyMaxMonths: 12, icon: 'briefcase', tone: 'navy',
    tags: ['business analysis', 'requirements', 'process improvement', 'operations', 'consulting'],
    dataSource: source('Management analysts', 'https://www.bls.gov/ooh/business-and-financial/management-analysts.htm'),
  },
  {
    _id: careerIds.financialAnalyst,
    slug: 'financial-analyst',
    title: 'Financial Analyst',
    domainId: domainIds.finance,
    summary: 'Evaluate financial performance, investment choices, and risk with disciplined analysis.',
    description: 'Financial analysts study financial statements, markets, business drivers, and economic conditions. They build models, compare scenarios, assess opportunities or risk, and communicate recommendations with clear assumptions.',
    educationPath: 'A bachelor degree in finance, accounting, economics, mathematics, or business is typical. Regulated activities and credentials vary by country. Portfolio work can demonstrate modeling, research, and clear investment or business reasoning.',
    requiredSkillIds: [skillIds.financialAnalysis, skillIds.dataAnalysis, skillIds.riskManagement, skillIds.criticalThinking, skillIds.presentation],
    responsibilities: ['Analyze statements, forecasts, and market information.', 'Build models and scenario comparisons.', 'Assess performance, value, or risk.', 'Present recommendations and assumptions.'],
    toolsToLearn: ['Excel', 'Financial databases', 'Presentation tools', 'SQL or Python (role dependent)'],
    traits: ['analytical', 'detail', 'communication'],
    salaryMin: 62_000, salaryMax: 180_000, salaryMedian: 101_350, salaryCurrency: 'USD', demand: 'high', growthPercent: 6,
    timeToJobReadyMinMonths: 6, timeToJobReadyMaxMonths: 18, icon: 'chart', tone: 'amber',
    tags: ['finance', 'investment', 'financial modeling', 'risk', 'analysis'],
    dataSource: source('Financial and investment analysts', 'https://www.bls.gov/ooh/business-and-financial/financial-analysts.htm'),
  },
  {
    _id: careerIds.registeredNurse,
    slug: 'registered-nurse',
    title: 'Registered Nurse',
    domainId: domainIds.healthcare,
    summary: 'Assess, coordinate, and deliver evidence-based care across healthcare settings.',
    description: 'Registered nurses assess patients, administer treatments, coordinate care, educate patients and families, maintain records, and respond to changes in condition. Work settings and specialties vary widely.',
    educationPath: 'Complete an approved nursing education program and meet every licensing requirement in the country or region where you intend to practise. Clinical placement and supervised competency assessment are essential; online study alone is not sufficient.',
    requiredSkillIds: [skillIds.patientCare, skillIds.clinicalPractice, skillIds.communication, skillIds.criticalThinking, skillIds.empathy],
    responsibilities: ['Assess patient needs and monitor changes.', 'Deliver and document care safely.', 'Coordinate with multidisciplinary teams.', 'Educate and advocate for patients and families.'],
    toolsToLearn: ['Electronic health records', 'Clinical monitoring equipment', 'Medication safety systems', 'Local care protocols'],
    traits: ['empathy', 'communication', 'resilience'],
    salaryMin: 66_000, salaryMax: 135_000, salaryMedian: 93_600, salaryCurrency: 'USD', demand: 'high', growthPercent: 5,
    timeToJobReadyMinMonths: 24, timeToJobReadyMaxMonths: 48, icon: 'heart', tone: 'rose',
    tags: ['healthcare', 'nursing', 'patient care', 'clinical', 'regulated career'],
    dataSource: source('Registered nurses', 'https://www.bls.gov/ooh/healthcare/registered-nurses.htm'),
  },
  {
    _id: careerIds.mechanicalEngineer,
    slug: 'mechanical-engineer',
    title: 'Mechanical Engineer',
    domainId: domainIds.engineering,
    summary: 'Design, analyze, prototype, and improve mechanical and thermal systems.',
    description: 'Mechanical engineers apply physics, mathematics, materials, and design methods to machines, devices, energy systems, manufacturing, and robotics. They analyze needs, create models, test prototypes, and investigate failures.',
    educationPath: 'A bachelor degree in mechanical engineering or mechanical engineering technology is typical. Licensing is required for some public engineering services and varies by location. Internships, labs, and design teams build important evidence.',
    requiredSkillIds: [skillIds.engineeringDesign, skillIds.cad, skillIds.problemSolving, skillIds.projectManagement, skillIds.teamwork],
    responsibilities: ['Analyze mechanical or thermal problems.', 'Create and review engineering designs.', 'Build and test prototypes.', 'Investigate failures and support manufacturing.'],
    toolsToLearn: ['CAD software', 'Simulation tools', 'MATLAB or Python', 'Testing and measurement equipment'],
    traits: ['analytical', 'technical', 'teamwork'],
    salaryMin: 65_000, salaryMax: 160_000, salaryMedian: 102_320, salaryCurrency: 'USD', demand: 'high', growthPercent: 9,
    timeToJobReadyMinMonths: 36, timeToJobReadyMaxMonths: 54, icon: 'settings', tone: 'navy',
    tags: ['engineering', 'mechanical', 'cad', 'manufacturing', 'robotics'],
    dataSource: source('Mechanical engineers', 'https://www.bls.gov/ooh/architecture-and-engineering/mechanical-engineers.htm'),
  },
  {
    _id: careerIds.learningDesigner,
    slug: 'learning-experience-designer',
    title: 'Learning Experience Designer',
    domainId: domainIds.education,
    summary: 'Design learning that helps people build and demonstrate useful skills.',
    description: 'Learning experience designers analyze learner needs, define outcomes, structure content and practice, create accessible learning materials, and evaluate whether instruction improves performance. Titles overlap with instructional design and training development.',
    educationPath: 'Education, instructional design, psychology, communications, and subject-matter backgrounds are common. A portfolio should show objectives, learner analysis, practice, accessibility, and evaluation rather than slides alone.',
    requiredSkillIds: [skillIds.instructionalDesign, skillIds.learningAssessment, skillIds.research, skillIds.communication, skillIds.uiDesign],
    responsibilities: ['Analyze learners, context, and performance needs.', 'Define measurable learning outcomes.', 'Create instruction, practice, and assessment.', 'Evaluate results and improve the experience.'],
    toolsToLearn: ['Authoring tools', 'Learning management systems', 'Video and audio editing', 'Accessibility checkers'],
    traits: ['creative', 'empathy', 'communication'],
    salaryMin: 45_000, salaryMax: 115_000, salaryMedian: 65_850, salaryCurrency: 'USD', demand: 'high', growthPercent: 11,
    timeToJobReadyMinMonths: 4, timeToJobReadyMaxMonths: 12, icon: 'book', tone: 'lavender',
    tags: ['education', 'instructional design', 'learning design', 'training', 'accessibility'],
    dataSource: source('Training and development specialists (BLS proxy)', 'https://www.bls.gov/ooh/business-and-financial/training-and-development-specialists.htm'),
  },
]

export const careersSeed = rawCareersSeed.map((career) => ({
  _id: career._id,
  slug: career.slug,
  title: career.title,
  summary: career.summary,
  description: career.description,
  domainId: career.domainId,
  requiredSkills: career.requiredSkillIds.map((skillId, index) => ({
    skillId,
    importance: index < 2 ? 'critical' : 'important',
    requiredLevel: Math.max(6, 8 - Math.floor(index / 2)),
  })),
  educationPath: career.educationPath,
  responsibilities: career.responsibilities,
  toolsToLearn: career.toolsToLearn,
  traits: career.traits,
  expectedSalary: {
    min: career.salaryMin,
    max: career.salaryMax,
    median: career.salaryMedian,
    currency: career.salaryCurrency,
  },
  dataSource: career.dataSource,
  demand: career.demand,
  growthRatePercent: career.growthPercent,
  timeToJobReady: {
    minMonths: career.timeToJobReadyMinMonths,
    maxMonths: career.timeToJobReadyMaxMonths,
  },
  iconKey: career.icon,
  colorTone: career.tone,
  tags: career.tags,
  status: 'published',
  publishedAt,
  active: true,
}))
