import { careerIds, domainIds, skillIds } from './ids.js'

const rawCareersSeed = [
  {
    _id: careerIds.uxDesigner,
    slug: 'ux-ui-designer',
    title: 'UX/UI Designer',
    domainId: domainIds.design,
    summary: 'Design experiences that make technology feel simple and intuitive.',
    description:
      'UX/UI Designers work closely with users, product managers, and engineers to research needs, test ideas, and refine every interaction across a digital product.',
    requiredSkillIds: [skillIds.uxResearch, skillIds.uiDesign, skillIds.prototyping, skillIds.creativity, skillIds.empathy],
    responsibilities: [
      'Interview users and turn research into clear problem statements.',
      'Sketch flows and build testable prototypes before development begins.',
      'Partner with engineers and product managers to refine the experience.',
    ],
    toolsToLearn: ['Figma', 'Miro', 'Notion', 'Maze'],
    traits: ['creative', 'empathy'],
    salaryMin: 55_000,
    salaryMax: 95_000,
    salaryCurrency: 'USD',
    demand: 'high',
    growthPercent: 13,
    timeToJobReadyMinMonths: 6,
    timeToJobReadyMaxMonths: 12,
    icon: 'pen',
    tone: 'violet',
    tags: ['design', 'ux', 'ui', 'product design', 'user research'],
    active: true,
  },
  {
    _id: careerIds.dataAnalyst,
    slug: 'data-analyst',
    title: 'Data Analyst',
    domainId: domainIds.dataAi,
    summary: 'Turn raw data into insights that guide real business decisions.',
    description:
      'Data Analysts collect, clean, and analyze data to answer business questions, then present findings through dashboards and reports that guide decisions.',
    requiredSkillIds: [skillIds.dataAnalysis, skillIds.sql, skillIds.python, skillIds.criticalThinking],
    responsibilities: [
      'Clean and organize raw data from multiple sources.',
      'Build dashboards and reports that answer specific business questions.',
      'Present findings clearly to non-technical stakeholders.',
    ],
    toolsToLearn: ['SQL', 'Excel', 'Power BI', 'Python'],
    traits: ['analytical', 'technical'],
    salaryMin: 58_000,
    salaryMax: 98_000,
    salaryCurrency: 'USD',
    demand: 'very_high',
    growthPercent: 23,
    timeToJobReadyMinMonths: 4,
    timeToJobReadyMaxMonths: 9,
    icon: 'chart',
    tone: 'blue',
    tags: ['data', 'analytics', 'sql', 'business intelligence'],
    active: true,
  },
  {
    _id: careerIds.softwareEngineer,
    slug: 'software-engineer',
    title: 'Software Engineer',
    domainId: domainIds.softwareEngineering,
    summary: 'Build the applications and systems that power everyday products.',
    description:
      'Software Engineers design, build, and maintain applications, working across the stack to turn requirements into reliable, working software.',
    requiredSkillIds: [skillIds.javascript, skillIds.react, skillIds.apiDesign, skillIds.problemSolving],
    responsibilities: [
      'Write, test, and maintain application code.',
      'Design APIs and data models for new features.',
      'Debug issues and collaborate on code reviews.',
    ],
    toolsToLearn: ['Git', 'VS Code', 'Node.js', 'React'],
    traits: ['technical', 'analytical'],
    salaryMin: 65_000,
    salaryMax: 130_000,
    salaryCurrency: 'USD',
    demand: 'very_high',
    growthPercent: 25,
    timeToJobReadyMinMonths: 6,
    timeToJobReadyMaxMonths: 12,
    icon: 'code',
    tone: 'green',
    tags: ['engineering', 'software', 'developer', 'programming'],
    active: true,
  },
  {
    _id: careerIds.digitalMarketer,
    slug: 'digital-marketing-specialist',
    title: 'Digital Marketing Specialist',
    domainId: domainIds.marketing,
    summary: 'Grow brands online through content, search, and campaigns.',
    description:
      'Digital Marketing Specialists plan and run campaigns across search, social, and content channels, tracking performance to grow an audience or business.',
    requiredSkillIds: [skillIds.digitalMarketing, skillIds.seo, skillIds.contentStrategy, skillIds.communication],
    responsibilities: [
      'Plan and launch campaigns across digital channels.',
      'Optimize content for search and audience engagement.',
      'Track performance metrics and report on campaign results.',
    ],
    toolsToLearn: ['Google Analytics', 'Meta Ads Manager', 'Mailchimp', 'SEMrush'],
    traits: ['creative', 'communication'],
    salaryMin: 45_000,
    salaryMax: 80_000,
    salaryCurrency: 'USD',
    demand: 'medium',
    growthPercent: 10,
    timeToJobReadyMinMonths: 3,
    timeToJobReadyMaxMonths: 8,
    icon: 'megaphone',
    tone: 'orange',
    tags: ['marketing', 'seo', 'content', 'social media'],
    active: true,
  },
  {
    _id: careerIds.cybersecurityAnalyst,
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    domainId: domainIds.cybersecurity,
    summary: 'Protect systems and data from threats and breaches.',
    description:
      "Cybersecurity Analysts monitor networks for threats, investigate incidents, and implement safeguards to protect an organization's systems and data.",
    requiredSkillIds: [skillIds.cybersecurity, skillIds.networkSecurity, skillIds.criticalThinking, skillIds.problemSolving],
    responsibilities: [
      'Monitor systems and networks for suspicious activity.',
      'Investigate and respond to security incidents.',
      'Recommend and implement security improvements.',
    ],
    toolsToLearn: ['Wireshark', 'Splunk', 'Nmap', 'Linux'],
    traits: ['technical', 'analytical'],
    salaryMin: 60_000,
    salaryMax: 110_000,
    salaryCurrency: 'USD',
    demand: 'very_high',
    growthPercent: 30,
    timeToJobReadyMinMonths: 6,
    timeToJobReadyMaxMonths: 12,
    icon: 'shield',
    tone: 'red',
    tags: ['cybersecurity', 'security', 'network', 'infosec'],
    active: true,
  },
  {
    _id: careerIds.productManager,
    slug: 'product-manager',
    title: 'Product Manager',
    domainId: domainIds.business,
    summary: 'Lead teams to build products people actually want.',
    description:
      'Product Managers define product strategy, prioritize what gets built, and align designers, engineers, and stakeholders around a shared roadmap.',
    requiredSkillIds: [skillIds.productStrategy, skillIds.communication, skillIds.leadership, skillIds.businessAnalysis],
    responsibilities: [
      'Define product strategy and prioritize the roadmap.',
      'Gather requirements from users and stakeholders.',
      'Align design and engineering teams around shared goals.',
    ],
    toolsToLearn: ['Jira', 'Notion', 'Figma', 'Amplitude'],
    traits: ['people', 'communication'],
    salaryMin: 70_000,
    salaryMax: 135_000,
    salaryCurrency: 'USD',
    demand: 'high',
    growthPercent: 19,
    timeToJobReadyMinMonths: 8,
    timeToJobReadyMaxMonths: 14,
    icon: 'target',
    tone: 'teal',
    tags: ['product', 'management', 'strategy', 'leadership'],
    active: true,
  },
]

export const careersSeed = rawCareersSeed.map((career) => ({
  _id: career._id,
  slug: career.slug,
  title: career.title,
  summary: career.summary,
  description: career.description,
  domainId: career.domainId,
  requiredSkills: career.requiredSkillIds.map((skillId, index) => ({
    skillId,
    importance: index < 2 ? 'critical' : 'important',
    requiredLevel: Math.max(6, 8 - Math.floor(index / 2)),
  })),
  responsibilities: career.responsibilities,
  toolsToLearn: career.toolsToLearn,
  traits: career.traits,
  expectedSalary: {
    min: career.salaryMin,
    max: career.salaryMax,
    currency: career.salaryCurrency,
  },
  demand: career.demand,
  growthRatePercent: career.growthPercent,
  timeToJobReady: {
    minMonths: career.timeToJobReadyMinMonths,
    maxMonths: career.timeToJobReadyMaxMonths,
  },
  iconKey: career.icon,
  colorTone: career.tone,
  tags: career.tags,
  status: 'published',
  publishedAt: new Date('2026-08-01T00:00:00.000Z'),
  active: career.active,
}))
