import { domainIds, skillIds } from './ids.js'

export const skillsSeed = [
  [skillIds.javascript, 'javascript', 'JavaScript', 'technical', ['JS', 'ECMAScript']],
  [skillIds.python, 'python', 'Python', 'technical', []],
  [skillIds.sql, 'sql', 'SQL', 'technical', ['Structured Query Language']],
  [skillIds.react, 'react', 'React', 'technical', ['ReactJS']],
  [skillIds.apiDesign, 'api-design', 'API Design', 'technical', ['REST API Design']],
  [skillIds.dataAnalysis, 'data-analysis', 'Data Analysis', 'analytical', ['Data Analytics']],
  [skillIds.cybersecurity, 'cybersecurity', 'Cybersecurity', 'technical', ['Information Security']],
  [skillIds.cloudComputing, 'cloud-computing', 'Cloud Computing', 'technical', []],
  [skillIds.uxResearch, 'ux-research', 'UX Research', 'research', ['User Research']],
  [skillIds.uiDesign, 'ui-design', 'UI Design', 'design', ['Interface Design']],
  [skillIds.prototyping, 'prototyping', 'Prototyping', 'design', []],
  [skillIds.seo, 'seo', 'Search Engine Optimization', 'business', ['SEO']],
  [skillIds.contentStrategy, 'content-strategy', 'Content Strategy', 'creative', []],
  [skillIds.financialAnalysis, 'financial-analysis', 'Financial Analysis', 'analytical', []],
  [skillIds.projectManagement, 'project-management', 'Project Management', 'management', []],
  [skillIds.productStrategy, 'product-strategy', 'Product Strategy', 'business', []],
  [skillIds.communication, 'communication', 'Communication', 'communication', []],
  [skillIds.teamwork, 'teamwork', 'Teamwork', 'communication', ['Collaboration']],
  [skillIds.leadership, 'leadership', 'Leadership', 'leadership', []],
  [skillIds.criticalThinking, 'critical-thinking', 'Critical Thinking', 'analytical', []],
  [skillIds.problemSolving, 'problem-solving', 'Problem Solving', 'analytical', []],
  [skillIds.creativity, 'creativity', 'Creativity', 'creative', []],
  [skillIds.empathy, 'empathy', 'Empathy', 'communication', []],
  [skillIds.presentation, 'presentation', 'Presentation', 'communication', ['Public Speaking']],
  [skillIds.research, 'research', 'Research', 'research', []],
  [skillIds.businessAnalysis, 'business-analysis', 'Business Analysis', 'business', []],
  [skillIds.digitalMarketing, 'digital-marketing', 'Digital Marketing', 'business', []],
  [skillIds.teaching, 'teaching', 'Teaching', 'communication', ['Instruction']],
  [skillIds.networkSecurity, 'network-security', 'Network Security', 'technical', []],
  [skillIds.machineLearning, 'machine-learning', 'Machine Learning', 'technical', ['ML']],
  [skillIds.statistics, 'statistics', 'Statistics', 'analytical', ['Statistical Analysis']],
  [skillIds.dataVisualization, 'data-visualization', 'Data Visualization', 'analytical', ['Data Viz']],
  [skillIds.cloudInfrastructure, 'cloud-infrastructure', 'Cloud Infrastructure', 'technical', ['Cloud Platforms']],
  [skillIds.devOps, 'devops', 'DevOps', 'technical', ['CI/CD']],
  [skillIds.softwareTesting, 'software-testing', 'Software Testing', 'technical', ['Quality Assurance']],
  [skillIds.testAutomation, 'test-automation', 'Test Automation', 'technical', ['Automated Testing']],
  [skillIds.riskManagement, 'risk-management', 'Risk Management', 'business', ['Risk Analysis']],
  [skillIds.patientCare, 'patient-care', 'Patient Care', 'communication', ['Patient Support']],
  [skillIds.clinicalPractice, 'clinical-practice', 'Clinical Practice', 'technical', ['Clinical Skills']],
  [skillIds.engineeringDesign, 'engineering-design', 'Engineering Design', 'technical', ['Product Engineering']],
  [skillIds.cad, 'cad', 'Computer-Aided Design', 'technical', ['CAD']],
  [skillIds.instructionalDesign, 'instructional-design', 'Instructional Design', 'design', ['Learning Design']],
  [skillIds.learningAssessment, 'learning-assessment', 'Learning Assessment', 'analytical', ['Assessment Design']],
  [skillIds.stakeholderManagement, 'stakeholder-management', 'Stakeholder Management', 'management', ['Stakeholder Engagement']],
].map(([_id, slug, name, category, aliases]) => ({
  _id,
  slug,
  name,
  category,
  aliases,
  active: true,
}))

export const domainsSeed = [
  [domainIds.softwareEngineering, 'software-engineering', 'Software Engineering', 'code'],
  [domainIds.dataAi, 'data-ai', 'Data & AI', 'chart'],
  [domainIds.design, 'design', 'Design', 'pen'],
  [domainIds.healthcare, 'healthcare', 'Healthcare', 'heart'],
  [domainIds.finance, 'finance', 'Finance', 'briefcase'],
  [domainIds.marketing, 'marketing', 'Marketing', 'megaphone'],
  [domainIds.education, 'education', 'Education', 'book'],
  [domainIds.engineering, 'engineering', 'Engineering', 'tool'],
  [domainIds.business, 'business', 'Business', 'target'],
  [domainIds.cybersecurity, 'cybersecurity', 'Cybersecurity', 'shield'],
].map(([_id, slug, name, icon], sortOrder) => ({
  _id,
  slug,
  name,
  icon,
  sortOrder,
  active: true,
}))
