import mongoose from 'mongoose'
import { careerIds, domainIds, userIds } from './ids.js'

const { ObjectId } = mongoose.Types

function deterministicId(namespace, sequence) {
  return new ObjectId(`${namespace}${sequence.toString(16).padStart(23, '0')}`)
}

export const resourceIds = Object.freeze({
  r1: deterministicId('8', 1),
  r2: deterministicId('8', 2),
  r3: deterministicId('8', 3),
  r4: deterministicId('8', 4),
  r5: deterministicId('8', 5),
  r6: deterministicId('8', 6),
})

export const mediaIds = Object.freeze({
  m1: deterministicId('9', 1),
  m2: deterministicId('9', 2),
  m3: deterministicId('9', 3),
  m4: deterministicId('9', 4),
  m5: deterministicId('9', 5),
  m6: deterministicId('9', 6),
})

export const storyIds = Object.freeze({
  s1: deterministicId('a', 1),
  s2: deterministicId('a', 2),
  s3: deterministicId('a', 3),
})

export const notificationIds = Object.freeze({
  n1: deterministicId('b', 1),
  n2: deterministicId('b', 2),
  n3: deterministicId('b', 3),
  n4: deterministicId('b', 4),
})

export const resourcesSeed = [
  {
    _id: resourceIds.r1,
    title: 'Career Decision Workbook',
    description: 'An original evidence-based workbook for comparing career possibilities, checking assumptions, and committing to a 30-day experiment.',
    type: 'pdf',
    file: {
      assetKey: 'documents/career-decision-workbook.pdf',
      url: '/assets/documents/career-decision-workbook.pdf',
      mimeType: 'application/pdf',
      originalName: 'career-decision-workbook.pdf',
      sizeBytes: 18_683,
    },
    pageCount: 10,
    tags: ['All careers', 'Planning', 'Decision making', 'Workbook'],
    relatedCareerIds: Object.values(careerIds),
    targetAudience: ['student', 'graduate', 'professional'],
    authorName: 'PathSeeker Editorial',
    version: '1.0',
    originalContent: true,
    sourceReferences: [
      { label: 'BLS Occupational Outlook Handbook', url: 'https://www.bls.gov/ooh/' },
      { label: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
      { label: 'CareerOneStop', url: 'https://www.careeronestop.org/' },
    ],
    lastReviewedAt: new Date('2026-08-27T00:00:00Z'),
    downloadCount: 142,
    status: 'published',
    publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: resourceIds.r2,
    title: 'UX Design Interview & Case Study Checklist',
    description: 'An original ethical-research checklist for planning interviews, synthesizing evidence, and presenting a credible UX case study.',
    type: 'checklist',
    file: {
      assetKey: 'documents/ux-interview-checklist.pdf',
      url: '/assets/documents/ux-interview-checklist.pdf',
      mimeType: 'application/pdf',
      originalName: 'ux-interview-checklist.pdf',
      sizeBytes: 15_728,
    },
    pageCount: 8,
    tags: ['UX Design', 'Design', 'Interview', 'Checklist'],
    relatedCareerIds: [careerIds.uxDesigner],
    targetAudience: ['student', 'graduate'],
    authorName: 'PathSeeker Editorial', version: '1.0', originalContent: true,
    sourceReferences: [
      { label: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
      { label: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/WAI/' },
    ],
    lastReviewedAt: new Date('2026-08-27T00:00:00Z'),
    downloadCount: 98,
    status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: resourceIds.r3,
    title: 'Junior Data Analyst 90-Day Roadmap',
    description: 'An original twelve-week, project-first plan covering spreadsheets, SQL, metrics, visualization, automation, and a finished capstone.',
    type: 'template',
    file: {
      assetKey: 'documents/data-analyst-roadmap.pdf',
      url: '/assets/documents/data-analyst-roadmap.pdf',
      mimeType: 'application/pdf',
      originalName: 'data-analyst-roadmap.pdf',
      sizeBytes: 18_108,
    },
    pageCount: 9,
    tags: ['Data & Business', 'Data Analysis', 'Roadmap'],
    relatedCareerIds: [careerIds.dataAnalyst, careerIds.dataScientist, careerIds.businessAnalyst],
    targetAudience: ['graduate', 'professional'],
    authorName: 'PathSeeker Editorial', version: '1.0', originalContent: true,
    sourceReferences: [
      { label: 'BLS Operations Research Analysts', url: 'https://www.bls.gov/ooh/math/operations-research-analysts.htm' },
      { label: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
    ],
    lastReviewedAt: new Date('2026-08-27T00:00:00Z'),
    downloadCount: 215,
    status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: resourceIds.r4,
    title: 'High-Impact Portfolio Guide for Tech & Design',
    description: 'An original guide to selecting stronger projects, explaining decisions and tradeoffs, proving outcomes, and publishing accessibly.',
    type: 'infographic',
    file: {
      assetKey: 'documents/portfolio-guide.pdf',
      url: '/assets/documents/portfolio-guide.pdf',
      mimeType: 'application/pdf',
      originalName: 'portfolio-guide.pdf',
      sizeBytes: 17_426,
    },
    pageCount: 9,
    tags: ['Career change', 'Portfolio', 'Design', 'Engineering'],
    relatedCareerIds: [careerIds.uxDesigner, careerIds.softwareEngineer, careerIds.qaEngineer, careerIds.cloudEngineer, careerIds.dataAnalyst],
    targetAudience: ['student', 'graduate', 'professional'],
    authorName: 'PathSeeker Editorial', version: '1.0', originalContent: true,
    sourceReferences: [
      { label: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
      { label: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/WAI/' },
    ],
    lastReviewedAt: new Date('2026-08-27T00:00:00Z'),
    downloadCount: 310,
    status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: resourceIds.r5,
    title: 'Tech Skills Gap Analysis & Practice Template',
    description: 'An original role-evidence template for separating ability from proof, prioritizing gaps, and planning a six-week practice sprint.',
    type: 'template',
    file: {
      assetKey: 'documents/skills-gap-template.pdf',
      url: '/assets/documents/skills-gap-template.pdf',
      mimeType: 'application/pdf',
      originalName: 'skills-gap-template.pdf',
      sizeBytes: 13_350,
    },
    pageCount: 7,
    tags: ['Skill-building', 'Assessment', 'Template'],
    relatedCareerIds: Object.values(careerIds),
    targetAudience: ['student', 'graduate', 'professional'],
    authorName: 'PathSeeker Editorial', version: '1.0', originalContent: true,
    sourceReferences: [
      { label: 'BLS Occupational Outlook Handbook', url: 'https://www.bls.gov/ooh/' },
      { label: 'CareerOneStop', url: 'https://www.careeronestop.org/' },
    ],
    lastReviewedAt: new Date('2026-08-27T00:00:00Z'),
    downloadCount: 87,
    status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: resourceIds.r6,
    title: 'Career Interview Preparation Pack',
    description: 'An original preparation pack for role research, evidence stories, work samples, mock interviews, and responsible follow-up.',
    type: 'checklist',
    file: {
      assetKey: 'documents/career-interview-preparation-pack.pdf',
      url: '/assets/documents/career-interview-preparation-pack.pdf',
      mimeType: 'application/pdf',
      originalName: 'career-interview-preparation-pack.pdf',
      sizeBytes: 15_240,
    },
    pageCount: 8,
    tags: ['All careers', 'Interview', 'Job search', 'Checklist'],
    relatedCareerIds: Object.values(careerIds),
    targetAudience: ['student', 'graduate', 'professional'],
    authorName: 'PathSeeker Editorial', version: '1.0', originalContent: true,
    sourceReferences: [
      { label: 'BLS Occupational Outlook Handbook', url: 'https://www.bls.gov/ooh/' },
      { label: 'CareerOneStop', url: 'https://www.careeronestop.org/' },
    ],
    lastReviewedAt: new Date('2026-08-27T00:00:00Z'),
    downloadCount: 0,
    status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
]

export const mediaSeed = [
  {
    _id: mediaIds.m1,
    title: 'Getting Hired as a Data Analyst',
    description: 'Google Career Certificates guidance on translating data-analysis practice into a focused job search and interview story.',
    type: 'video',
    url: 'https://www.youtube-nocookie.com/embed/X_bHxrgaqas',
    externalUrl: 'https://www.youtube.com/watch?v=X_bHxrgaqas',
    thumbnailUrl: 'https://i.ytimg.com/vi/X_bHxrgaqas/hqdefault.jpg',
    publisherName: 'Google Career Certificates',
    publisherUrl: 'https://www.youtube.com/@googlecareercertificates',
    learningObjectives: ['Connect portfolio evidence to entry-level analyst roles.', 'Prepare for data-focused interviews.', 'Plan a realistic job-search workflow.'],
    transcript: '00:00 - PathSeeker note: Use the player captions for the publisher-provided transcript.\n00:01 - Focus your application on evidence: a clear question, validated analysis, and an understandable recommendation.\n00:02 - Prepare to explain how you cleaned data, checked assumptions, and communicated limitations.',
    tags: ['Data & AI', 'Data Analysis', 'Video', 'Job Search'],
    relatedCareerIds: [careerIds.dataAnalyst],
    ratingAvg: 4.8, ratingCount: 45, status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: mediaIds.m2,
    title: 'UX Design Careers',
    description: 'A concise overview from Google Career Certificates of entry-level UX roles, portfolio pathways, internships, apprenticeships, and freelance experience.',
    type: 'video',
    url: 'https://www.youtube-nocookie.com/embed/CDo4dPywm4o',
    externalUrl: 'https://www.youtube.com/watch?v=CDo4dPywm4o',
    thumbnailUrl: 'https://i.ytimg.com/vi/CDo4dPywm4o/hqdefault.jpg',
    publisherName: 'Google Career Certificates', publisherUrl: 'https://www.youtube.com/@googlecareercertificates',
    learningObjectives: ['Recognize common UX entry roles.', 'Understand why case studies and portfolios matter.', 'Compare internship, apprenticeship, freelance, and junior-role routes.'],
    transcript: '00:00 - PathSeeker note: Use the player captions for the publisher-provided transcript.\n00:01 - UX work begins with understanding people and defining the problem before selecting a solution.\n00:02 - A portfolio should show the process from research through prototypes, testing, and iteration.',
    tags: ['UX Design', 'Design', 'Video', 'Career Path'],
    relatedCareerIds: [careerIds.uxDesigner],
    ratingAvg: 4.9, ratingCount: 62, status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: mediaIds.m3,
    title: 'Prepare for a Cybersecurity Career',
    description: 'Google Career Certificates guidance on security decisions, incident communication, professional communities, applications, and interviews.',
    type: 'video',
    url: 'https://www.youtube-nocookie.com/embed/3EgYr7jR4NI',
    externalUrl: 'https://www.youtube.com/watch?v=3EgYr7jR4NI',
    thumbnailUrl: 'https://i.ytimg.com/vi/3EgYr7jR4NI/hqdefault.jpg',
    publisherName: 'Google Career Certificates', publisherUrl: 'https://www.youtube.com/@googlecareercertificates',
    durationLabel: '86 min',
    learningObjectives: ['Understand ethical incident escalation.', 'Communicate security findings to stakeholders.', 'Prepare an entry-level security resume and interview pitch.'],
    transcript: '00:00 - PathSeeker note: Use the player captions and chapters for the publisher-provided transcript.\n02:51 - Learning focus: event and incident detection.\n31:48 - Learning focus: communicate for impact.\n55:23 - Learning focus: prepare for cybersecurity jobs and interviews.',
    tags: ['Cybersecurity', 'Security', 'Video', 'Career Preparation'],
    relatedCareerIds: [careerIds.cybersecurityAnalyst, careerIds.cloudEngineer],
    ratingAvg: 4.8, ratingCount: 29, status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: mediaIds.m4,
    title: 'Project Manager Careers',
    description: 'Google Career Certificates practitioners explain entry-level project responsibilities, transferable skills, and how project roles vary.',
    type: 'video',
    url: 'https://www.youtube-nocookie.com/embed/vmwjaY13NPA',
    externalUrl: 'https://www.youtube.com/watch?v=vmwjaY13NPA',
    thumbnailUrl: 'https://i.ytimg.com/vi/vmwjaY13NPA/hqdefault.jpg',
    publisherName: 'Google Career Certificates', publisherUrl: 'https://www.youtube.com/@googlecareercertificates',
    durationLabel: '18 min',
    learningObjectives: ['Recognize entry-level project responsibilities.', 'Identify transferable coordination skills.', 'Compare common project role titles.'],
    transcript: '00:00 - Introduction to project management.\n02:09 - Learning focus: what project management means.\n06:32 - Learning focus: what a project manager does.\n09:41 - Learning focus: transferable project skills.\n18:21 - Learning focus: finding a suitable role.',
    tags: ['Business', 'Project Management', 'Video', 'Career Path'],
    relatedCareerIds: [careerIds.projectManager, careerIds.productManager],
    ratingAvg: 4.7, ratingCount: 18, status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'),
    active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: mediaIds.m5,
    title: 'Jobs in Digital Marketing and E-Commerce',
    description: 'Google Career Certificates explains the entry-level digital marketing and e-commerce job landscape and practical next steps.',
    type: 'video',
    url: 'https://www.youtube-nocookie.com/embed/Xd1E2eQ5YZ8',
    externalUrl: 'https://www.youtube.com/watch?v=Xd1E2eQ5YZ8',
    thumbnailUrl: 'https://i.ytimg.com/vi/Xd1E2eQ5YZ8/hqdefault.jpg',
    publisherName: 'Google Career Certificates', publisherUrl: 'https://www.youtube.com/@googlecareercertificates',
    learningObjectives: ['Compare digital marketing and e-commerce role families.', 'Identify portfolio-ready campaign evidence.', 'Plan a focused entry-level search.'],
    transcript: '00:00 - PathSeeker note: Use the player captions for the publisher-provided transcript.\n00:01 - Map job titles to the channel, customer, and business outcome they support.\n00:02 - Build evidence through a small campaign plan, measurement framework, and reflection.',
    tags: ['Marketing', 'E-Commerce', 'Video', 'Job Search'],
    relatedCareerIds: [careerIds.digitalMarketer],
    ratingAvg: 4.7, ratingCount: 21, status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'), active: true,
    createdBy: userIds.superAdmin,
  },
  {
    _id: mediaIds.m6,
    title: 'Welcome to IT Support',
    description: 'A Google Career Certificates overview of troubleshooting, customer support, networking, operating systems, administration, and security.',
    type: 'video',
    url: 'https://www.youtube-nocookie.com/embed/lJC_sJ6jhDo',
    externalUrl: 'https://www.youtube.com/watch?v=lJC_sJ6jhDo',
    thumbnailUrl: 'https://i.ytimg.com/vi/lJC_sJ6jhDo/hqdefault.jpg',
    publisherName: 'Google Career Certificates', publisherUrl: 'https://www.youtube.com/@googlecareercertificates',
    durationLabel: '5 min',
    learningObjectives: ['Understand the scope of entry-level IT support.', 'Connect troubleshooting with customer communication.', 'Identify foundations that can lead toward cloud or cybersecurity.'],
    transcript: '00:00 - PathSeeker note: Use the player captions for the publisher-provided transcript.\n00:01 - IT support combines technical troubleshooting with clear and respectful customer care.\n00:02 - Networking, operating systems, administration, and security form a pathway into broader infrastructure roles.',
    tags: ['IT Support', 'Cloud', 'Cybersecurity', 'Video'],
    relatedCareerIds: [careerIds.cloudEngineer, careerIds.cybersecurityAnalyst, careerIds.softwareEngineer],
    ratingAvg: 4.8, ratingCount: 34, status: 'published', publishedAt: new Date('2026-08-27T00:00:00Z'), active: true,
    createdBy: userIds.superAdmin,
  },
]

export const storiesSeed = [
  {
    _id: storyIds.s1,
    submittedBy: userIds.graduate,
    authorName: 'Aisha Rahman',
    domainId: domainIds.design,
    storyText: 'After graduating with a psychology degree, I knew I wanted people-centered work but could not see how my background connected to technology. A PathSeeker quiz surfaced UX design and research roles. Instead of enrolling in another long degree, I tested the waters with a small campus project. Once I stopped trying to hide my background, everything clicked. Understanding people was exactly the point. Four months later, I accepted my first junior UX role at Looma.',
    image: {
      url: '/assets/avatars/aisha.png',
      mimeType: 'image/png',
      filename: 'aisha.png',
    },
    status: 'approved',
    isDemo: true,
    isDemo: true,
    approvedBy: userIds.superAdmin,
    approvedAt: new Date('2026-08-20T10:00:00Z'),
  },
  {
    _id: storyIds.s2,
    submittedBy: userIds.professional,
    authorName: 'Daniel Kim',
    domainId: domainIds.dataAi,
    storyText: 'I worked in retail logistics for five years and realized I enjoyed the spreadsheet optimization far more than floor operations. PathSeeker gave me a structured roadmap to learn SQL and Python while keeping my day job. Within 8 months, I pivoted into a Data Analyst position helping our supply chain forecasting team.',
    image: {
      url: '/assets/avatars/daniel.png',
      mimeType: 'image/png',
      filename: 'daniel.png',
    },
    status: 'approved',
    isDemo: true,
    isDemo: true,
    approvedBy: userIds.superAdmin,
    approvedAt: new Date('2026-08-22T14:30:00Z'),
  },
  {
    _id: storyIds.s3,
    submittedBy: userIds.student,
    authorName: 'Fatima Noor',
    domainId: domainIds.softwareEngineering,
    storyText: 'As a pre-engineering student, I felt overwhelmed by conflicting advice on web dev vs AI vs systems. PathSeeker’s Career Simulator showed me how frontend fundamentals combine with product thinking. Building my first open-source project gave me the confidence to secure a competitive software engineering internship.',
    image: {
      url: '/assets/avatars/fatima.png',
      mimeType: 'image/png',
      filename: 'fatima.png',
    },
    status: 'approved',
    isDemo: true,
    isDemo: true,
    approvedBy: userIds.superAdmin,
    approvedAt: new Date('2026-08-24T09:15:00Z'),
  },
]

export const notificationsSeed = [
  {
    _id: notificationIds.n1,
    userId: userIds.student,
    type: 'match',
    title: 'Your career matches are ready',
    body: 'Navi found top career paths that align with your latest assessment signals and profile strengths.',
    icon: 'sparkles',
    read: false,
    createdAt: new Date(Date.now() - 8 * 60 * 1000),
  },
  {
    _id: notificationIds.n2,
    userId: userIds.student,
    type: 'resource',
    title: 'A saved resource has a new lesson',
    body: 'UX Research: Start with Why added a practical interview worksheet.',
    icon: 'book',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    _id: notificationIds.n3,
    userId: userIds.student,
    type: 'feedback',
    title: 'The PathSeeker team replied',
    body: 'Your career comparison suggestions have been added to our roadmap.',
    icon: 'message',
    read: true,
    readAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    _id: notificationIds.n4,
    userId: userIds.student,
    type: 'reminder',
    title: 'Keep your Career Passport current',
    body: 'Add one recent project or skill to improve your compatibility score.',
    icon: 'target',
    read: true,
    readAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
]
