import { domainIds, quizQuestionIds } from './ids.js'

const rawQuizQuestionsSeed = [
  {
    _id: quizQuestionIds.q1,
    order: 1,
    eyebrow: 'Getting started',
    question: 'When you start a new project, what excites you most?',
    hint: 'Go with your first instinct.',
    type: 'multiple_choice',
    options: [
      { label: 'Sketching how it could look and feel', icon: 'pen', trait: 'creative' },
      { label: 'Figuring out the data behind it', icon: 'chart', trait: 'analytical' },
      { label: 'Rallying the team around a plan', icon: 'users', trait: 'people' },
      { label: 'Figuring out how to build it', icon: 'code', trait: 'technical' },
    ],
    active: true,
  },
  {
    _id: quizQuestionIds.q2,
    order: 2,
    eyebrow: 'Working with others',
    question: 'In a group project, which role do you naturally take?',
    hint: 'Think about your last group project.',
    type: 'multiple_choice',
    options: [
      { label: 'The one who explains ideas clearly', icon: 'message', trait: 'communication' },
      { label: 'The one who checks in on how everyone feels', icon: 'heart', trait: 'empathy' },
      { label: 'The one who keeps everything on schedule', icon: 'calendar', trait: 'organization' },
      { label: 'The one who leads and makes decisions', icon: 'users', trait: 'people' },
    ],
    active: true,
  },
  {
    _id: quizQuestionIds.q3,
    order: 3,
    eyebrow: 'Problem solving',
    question: "You're given a messy problem with no clear answer. What's your first move?",
    hint: "There's no wrong answer here.",
    type: 'multiple_choice',
    options: [
      { label: 'Break it into smaller, logical pieces', icon: 'chart', trait: 'analytical' },
      { label: 'Sketch a few different possible solutions', icon: 'pen', trait: 'creative' },
      { label: 'Try building a quick working version', icon: 'code', trait: 'technical' },
      { label: 'Ask people affected what they actually need', icon: 'heart', trait: 'empathy' },
    ],
    active: true,
  },
  {
    _id: quizQuestionIds.q4,
    order: 4,
    eyebrow: 'A good day at work',
    question: 'What would make a work day feel genuinely satisfying?',
    hint: 'Picture your ideal Tuesday.',
    type: 'multiple_choice',
    options: [
      { label: 'Finishing everything on my to-do list', icon: 'calendar', trait: 'organization' },
      { label: 'Having a great conversation that changes someone\u2019s mind', icon: 'message', trait: 'communication' },
      { label: 'Solving a tricky technical bug', icon: 'code', trait: 'technical' },
      { label: 'Helping a teammate who was struggling', icon: 'heart', trait: 'empathy' },
    ],
    active: true,
  },
  {
    _id: quizQuestionIds.q5,
    order: 5,
    eyebrow: 'Learning something new',
    question: 'When learning a new skill, what pulls you in?',
    hint: 'Think about something you learned recently.',
    type: 'multiple_choice',
    options: [
      { label: 'Understanding the underlying logic or numbers', icon: 'chart', trait: 'analytical' },
      { label: 'Making something visually interesting with it', icon: 'pen', trait: 'creative' },
      { label: 'Teaching it to someone else', icon: 'message', trait: 'communication' },
      { label: 'Organizing it into a clear step-by-step system', icon: 'calendar', trait: 'organization' },
    ],
    active: true,
  },
  {
    _id: quizQuestionIds.q6,
    order: 6,
    eyebrow: 'Under pressure',
    question: 'When a deadline is tight, what do you focus on first?',
    hint: 'Be honest with yourself.',
    type: 'multiple_choice',
    options: [
      { label: 'Making a clear plan and checklist', icon: 'calendar', trait: 'organization' },
      { label: 'Getting the team aligned fast', icon: 'users', trait: 'people' },
      { label: 'Just diving in and building', icon: 'code', trait: 'technical' },
      { label: 'Making sure no one is left confused or stressed', icon: 'heart', trait: 'empathy' },
    ],
    active: true,
  },
  {
    _id: quizQuestionIds.q7,
    order: 7,
    eyebrow: 'Looking ahead',
    question: 'Which achievement would make you proudest a year from now?',
    hint: 'Think big picture.',
    type: 'multiple_choice',
    options: [
      { label: 'Built something technically impressive', icon: 'code', trait: 'technical' },
      { label: 'Led a team to a great outcome', icon: 'users', trait: 'people' },
      { label: 'Created something people found beautiful or useful', icon: 'pen', trait: 'creative' },
      { label: 'Became known as a clear, trusted communicator', icon: 'message', trait: 'communication' },
    ],
    active: true,
  },
]

const traitDomains = {
  creative: [domainIds.design, domainIds.marketing],
  analytical: [domainIds.dataAi, domainIds.finance],
  people: [domainIds.business, domainIds.education],
  technical: [domainIds.softwareEngineering, domainIds.cybersecurity],
  communication: [domainIds.marketing, domainIds.business],
  empathy: [domainIds.design, domainIds.healthcare],
  organization: [domainIds.business, domainIds.engineering],
}

export const quizQuestionsSeed = rawQuizQuestionsSeed.map((question, questionIndex) => ({
  _id: question._id,
  questionText: question.question,
  eyebrow: question.eyebrow,
  hint: question.hint,
  type: question.type,
  order: question.order,
  timeLimitSeconds: 90,
  options: question.options.map((option, optionIndex) => ({
    key: String.fromCharCode(97 + optionIndex),
    label: option.label,
    icon: option.icon,
    trait: option.trait,
    domainWeights: (traitDomains[option.trait] || []).map((domainId, index) => ({
      domainId,
      weight: index === 0 ? 3 : 2,
    })),
  })),
  active: question.active,
}))
