import Icon from '../Icon'
import SectionHead from './SectionHead'


export default function SettingsForm({ section }) {
  if (section === 'Notifications') return <><SectionHead eyebrow="Stay informed" title="Notification preferences" />{['Weekly career insights', 'New resources for saved careers', 'Learning reminders', 'Product updates'].map((item, i) => <label className="toggle-row" key={item}><span><strong>{item}</strong><small>{i === 0 ? 'A short personalized digest every Monday' : 'Helpful updates, never noise'}</small></span><input type="checkbox" defaultChecked={i < 3} /><i /></label>)}</>
  if (section === 'Privacy & data') return <><SectionHead eyebrow="Your control" title="Privacy & data" /><div className="privacy-list"><button><span><Icon name="download" /></span><p><strong>Download my data</strong><small>Get a copy of your profile, quiz answers, notes, and saved content.</small></p><Icon name="chevron" /></button><button><span><Icon name="shield" /></span><p><strong>AI personalization</strong><small>Choose whether activity can improve your recommendations.</small></p><Icon name="chevron" /></button><button className="danger"><span><Icon name="close" /></span><p><strong>Delete account</strong><small>Permanently remove your PathSeeker account and data.</small></p><Icon name="chevron" /></button></div></>
  return <><SectionHead eyebrow="Account settings" title={section} /><div className="form-grid"><label>Full name<input defaultValue="Alex Morgan" /></label><label>Email address<input defaultValue="alex@example.com" /></label><label>Current stage<select defaultValue="Student"><option>Student</option><option>Graduate</option><option>Working professional</option></select></label><label>Location<input defaultValue="Karachi, Pakistan" /></label><label className="full">Short bio<textarea defaultValue="Curious student exploring careers where design, technology, and helping people come together." /></label></div><button className="button primary">Save changes</button></>
}
