// Development/showcase fixture data only. Production pages use services/pathseekerApi.js.
export const careers = [
  {
    id: 'ux-designer',
    title: 'UX Designer',
    field: 'Design & Technology',
    match: 94,
    salary: '$72k – $118k',
    demand: 'High demand',
    growth: '+13%',
    icon: 'pen',
    tone: 'lavender',
    skills: ['User research', 'Figma', 'Prototyping', 'Empathy'],
    summary: 'Shape intuitive digital products by understanding people and turning their needs into thoughtful experiences.',
  },
  {
    id: 'data-analyst',
    title: 'Data Analyst',
    field: 'Data & Business',
    match: 91,
    salary: '$68k – $105k',
    demand: 'Very high',
    growth: '+23%',
    icon: 'chart',
    tone: 'blue',
    skills: ['SQL', 'Data stories', 'Excel', 'Critical thinking'],
    summary: 'Turn complex information into clear insights that help teams make confident decisions.',
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    field: 'Business & Technology',
    match: 88,
    salary: '$86k – $142k',
    demand: 'High demand',
    growth: '+10%',
    icon: 'briefcase',
    tone: 'amber',
    skills: ['Strategy', 'Communication', 'Roadmaps', 'Leadership'],
    summary: 'Guide cross-functional teams to build products that solve valuable customer problems.',
  },
  {
    id: 'software-engineer',
    title: 'Software Engineer',
    field: 'Engineering',
    match: 84,
    salary: '$82k – $148k',
    demand: 'Very high',
    growth: '+25%',
    icon: 'code',
    tone: 'mint',
    skills: ['JavaScript', 'Problem solving', 'APIs', 'Teamwork'],
    summary: 'Design and build useful software systems, from user-facing apps to large-scale platforms.',
  },
  {
    id: 'digital-marketer',
    title: 'Digital Marketer',
    field: 'Marketing & Media',
    match: 79,
    salary: '$55k – $96k',
    demand: 'Growing',
    growth: '+8%',
    icon: 'megaphone',
    tone: 'rose',
    skills: ['Content', 'Analytics', 'SEO', 'Creativity'],
    summary: 'Connect brands and audiences through memorable campaigns, content, and measurable growth.',
  },
  {
    id: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    field: 'Security & Technology',
    match: 76,
    salary: '$78k – $132k',
    demand: 'Very high',
    growth: '+32%',
    icon: 'shield',
    tone: 'navy',
    skills: ['Security', 'Networks', 'Risk analysis', 'Curiosity'],
    summary: 'Protect people and organizations by finding risks and strengthening digital systems.',
  },
]

export const resources = [
  { type: 'Course', title: 'UX Research: Start with Why', meta: '42 min · Beginner', progress: 62, icon: 'play', tone: 'lavender' },
  { type: 'Podcast', title: 'How I broke into product design', meta: '28 min · Maya Chen', progress: 0, icon: 'headphones', tone: 'mint' },
  { type: 'Toolkit', title: 'Career decision workbook', meta: 'PDF · 18 pages', progress: 0, icon: 'file', tone: 'amber' },
  { type: 'Video', title: 'A day in the life of a data analyst', meta: '12 min · Expert story', progress: 0, icon: 'video', tone: 'blue' },
  { type: 'Guide', title: 'Build a portfolio that gets noticed', meta: '8 min read', progress: 35, icon: 'book', tone: 'rose' },
  { type: 'Podcast', title: 'The skills employers need next', meta: '36 min · Future of Work', progress: 0, icon: 'mic', tone: 'navy' },
]

export const stories = [
  {
    name: 'Aisha Rahman',
    role: 'Junior UX Designer at Looma',
    quote: 'PathSeeker helped me see that my psychology degree was a strength—not a detour. I landed my first UX role in five months.',
    initials: 'AR',
    tone: 'mint',
  },
  {
    name: 'Daniel Kim',
    role: 'Data Analyst at Northstar',
    quote: 'The roadmap made a huge career change feel manageable. I always knew the next small skill to focus on.',
    initials: 'DK',
    tone: 'blue',
  },
  {
    name: 'Fatima Noor',
    role: 'Product Associate at Bloom',
    quote: 'Navi asked the questions I could not ask myself. My recommendation finally connected all the things I enjoy.',
    initials: 'FN',
    tone: 'lavender',
  },
]

export const navItems = [
  { id: 'dashboard', label: 'Overview', icon: 'home' },
  { id: 'quiz', label: 'Career quiz', icon: 'sparkles' },
  { id: 'recommendations', label: 'My matches', icon: 'target' },
  { id: 'careers', label: 'Career Bank', icon: 'compass' },
  { id: 'resources', label: 'Resources', icon: 'library' },
  { id: 'saved', label: 'Saved & notes', icon: 'bookmark' },
  { id: 'stories', label: 'Success stories', icon: 'users' },
]

export const quizQuestions = [
  {
    eyebrow: 'How you like to work',
    question: 'Which kind of challenge gives you the most energy?',
    hint: 'There is no wrong answer. Choose the one that feels most like you.',
    options: [
      ['Making something easier and more beautiful to use', 'pen'],
      ['Finding patterns hidden inside lots of information', 'chart'],
      ['Bringing people together around one clear plan', 'users'],
      ['Building a solution and making every part work', 'code'],
    ],
  },
  {
    eyebrow: 'Your natural strengths',
    question: 'What do friends or teammates usually ask you for help with?',
    hint: 'Think about what comes naturally—even if it feels ordinary to you.',
    options: [
      ['Making ideas clear and easy to understand', 'message'],
      ['Solving a tricky technical problem', 'code'],
      ['Organizing a group and keeping things moving', 'calendar'],
      ['Listening and helping people feel understood', 'heart'],
    ],
  },
]
