import Icon from '../../components/Icon'
import Head from '../../components/admin/AdminEditorHead'
import Field from '../../components/admin/AdminField'
import { useState } from 'react'

export default function AdminContentEditor({ navigate }) {
  const [format, setFormat] = useState('Video')
  return <div className="admin-stack"><Head eyebrow="Learning library · Editor" title="Add content" copy="Create a frontend record ready for the future content API and media storage."><button className="button ghost" onClick={() => navigate('admin-content')}>Cancel</button><button className="button soft">Save draft</button><button className="button primary">Publish content</button></Head><div className="admin-editor-layout"><section className="panel admin-editor-form"><div className="editor-section"><h2>Content details</h2><div className="form-grid"><Field label="Title"><input defaultValue="Design interviews that uncover real needs" /></Field><Field label="Format"><select value={format} onChange={(event) => setFormat(event.target.value)}><option>Video</option><option>Podcast</option><option>Course</option><option>Document</option></select></Field><Field label="Description"><textarea defaultValue="A practical guide to planning and running a useful research interview." /></Field><Field label="Author"><input defaultValue="Maya Chen" /></Field></div></div><div className="editor-section"><h2>{format === 'Document' ? 'Document file' : 'Media source'}</h2><div className="upload-zone"><Icon name={format === 'Document' ? 'file' : 'video'} size={30} /><strong>Drop a file here or browse</strong><small>Frontend preview only · the backend can later use S3, Cloudinary, or GridFS metadata.</small><button className="button soft">Choose file</button></div></div><div className="editor-section"><h2>Discovery</h2><div className="tag-editor">{['UX Design','Beginner','Skill-building'].map((tag) => <span key={tag}>{tag}<button>×</button></span>)}<button><Icon name="plus" /> Add tag</button></div></div></section><aside className="panel publish-checklist"><span className="eyebrow">Before publishing</span><h3>Content checklist</h3>{['Title and description','Accessible transcript','Career tags','Preview image','Usage rights'].map((item, index) => <p key={item}><Icon name={index < 3 ? 'check' : 'clock'} />{item}</p>)}</aside></div></div>
}
