import { careerIds, domainIds, skillIds } from './ids.js'

export const careersSeed = [
  {
    _id: careerIds.uxDesigner,
    slug: 'ux-ui-designer',
    title: 'UX/UI Designer',
    domainId: domainIds.design,
    summary: 'Design experiences that make technology feel simple and intuitive.',
    description:
      'UX/UI Designers work closely with users, product managers, and engineers to research needs, test ideas, and refine every interaction across a digital product.',
    requiredSkills: [
      { skillId: skillIds.uxResearch, importance: 'critical' },
      { skillId: skillIds.uiDesign, importance: 'critical' },
      { skillId: skillIds.prototyping, importance: 'important' },
      { skillId: skillIds.creativity, importance: 'important' },
      { skillId: skillIds.empathy, importance: 'important' },
    ],
    responsibilities: [
      'Interview users and turn research into clear problem statements.',
      'Sketch flows and build testable prototypes before development begins.',
      'Partner with engineers and product managers to refine the experience.',
    ],
    toolsToLearn: ['Figma', 'Miro', 'Notion', 'Maze'],
    traits: ['creative', 'empathy'],
    expectedSalary: { min: 55_000, max: 95_000, currency: 'USD' },
    demand: 'high',
    growthRatePercent: 13,
    timeToJobReadyMinMonths: 6,
    timeToJobReadyMaxMonths: 12,
    iconKey: 'pen',
    colorTone: 'violet',
    tags: ['design', 'ux', 'ui', 'product design', 'user research'],
    active: true,
  },
  {
    _id: careerIds.dataAnalyst,
    slug: 'data-analyst',
    title: 'Data Analyst',
    domainId: domainIds.dataAi,
    summary: 'Turn raw data into insights that guide real business decisions.',
    description:
      'Data Analysts collect, clean, and analyze data to answer business questions, then present findings through dashboards and reports that guide decisions.',
    requiredSkills: [
      { skillId: skillIds.dataAnalysis, importance: 'critical' },
      { skillId: skillIds.sql, importance: 'critical' },
      { skillId: skillIds.python, importance: 'important' },
      { skillId: skillIds.criticalThinking, importance: 'important' },
    ],
    responsibilities: [
      'Clean and organize raw data from multiple sources.',
      'Build dashboards and reports that answer specific business questions.',
      'Present findings clearly to non-technical stakeholders.',
    ],
    toolsToLearn: ['SQL', 'Excel', 'Power BI', 'Python'],
    traits: ['analytical', 'technical'],
    expectedSalary: { min: 58_000, max: 98_000, currency: 'USD' },
    demand: 'very_high',
    growthRatePercent: 23,
    timeToJobReadyMinMonths: 4,
    timeToJobReadyMaxMonths: 9,
    iconKey: 'chart',
    colorTone: 'blue',
    tags: ['data', 'analytics', 'sql', 'business intelligence'],
    active: true,
  },
  {
    _id: careerIds.softwareEngineer,
    slug: 'software-engineer',
    title: 'Software Engineer',
    domainId: domainIds.softwareEngineering,
    summary: 'Build the applications and systems that power everyday products.',
    description:
      'Software Engineers design, build, and maintain applications, working across the stack to turn requirements into reliable, working software.',
    requiredSkills: [
      { skillId: skillIds.javascript, importance: 'critical' },
      { skillId: skillIds.react, importance: 'important' },
      { skillId: skillIds.apiDesign, importance: 'important' },
      { skillId: skillIds.problemSolving, importance: 'critical' },
    ],
    responsibilities: [
      'Write, test, and maintain application code.',
      'Design APIs and data models for new features.',
      'Debug issues and collaborate on code reviews.',
    ],
    toolsToLearn: ['Git', 'VS Code', 'Node.js', 'React'],
    traits: ['technical', 'analytical'],
    expectedSalary: { min: 65_000, max: 130_000, currency: 'USD' },
    demand: 'very_high',
    growthRatePercent: 25,
    timeToJobReadyMinMonths: 6,
    timeToJobReadyMaxMonths: 12,
    iconKey: 'code',
    colorTone: 'green',
    tags: ['engineering', 'software', 'developer', 'programming'],
    active: true,
  },
  {
    _id: careerIds.digitalMarketer,
    slug: 'digital-marketing-specialist',
    title: 'Digital Marketing Specialist',
    domainId: domainIds.marketing,
    summary: 'Grow brands online through content, search, and campaigns.',
    description:
      'Digital Marketing Specialists plan and run campaigns across search, social, and content channels, tracking performance to grow an audience or business.',
    requiredSkills: [
      { skillId: skillIds.digitalMarketing, importance: 'critical' },
      { skillId: skillIds.seo, importance: 'important' },
      { skillId: skillIds.contentStrategy, importance: 'important' },
      { skillId: skillIds.communication, importance: 'important' },
    ],
    responsibilities: [
      'Plan and launch campaigns across digital channels.',
      'Optimize content for search and audience engagement.',
      'Track performance metrics and report on campaign results.',
    ],
    toolsToLearn: ['Google Analytics', 'Meta Ads Manager', 'Mailchimp', 'SEMrush'],
    traits: ['creative', 'communication'],
    expectedSalary: { min: 45_000, max: 80_000, currency: 'USD' },
    demand: 'medium',
    growthRatePercent: 10,
    timeToJobReadyMinMonths: 3,
    timeToJobReadyMaxMonths: 8,
    iconKey: 'megaphone',
    colorTone: 'orange',
    tags: ['marketing', 'seo', 'content', 'social media'],
    active: true,
  },
  {
    _id: careerIds.cybersecurityAnalyst,
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    domainId: domainIds.cybersecurity,
    summary: 'Protect systems and data from threats and breaches.',
    description:
      "Cybersecurity Analysts monitor networks for threats, investigate incidents, and implement safeguards to protect an organization's systems and data.",
    requiredSkills: [
      { skillId: skillIds.cybersecurity, importance: 'critical' },
      { skillId: skillIds.networkSecurity, importance: 'critical' },
      { skillId: skillIds.criticalThinking, importance: 'important' },
      { skillId: skillIds.problemSolving, importance: 'important' },
    ],
    responsibilities: [
      'Monitor systems and networks for suspicious activity.',
      'Investigate and respond to security incidents.',
      'Recommend and implement security improvements.',
    ],
    toolsToLearn: ['Wireshark', 'Splunk', 'Nmap', 'Linux'],
    traits: ['technical', 'analytical'],
    expectedSalary: { min: 60_000, max: 110_000, currency: 'USD' },
    demand: 'very_high',
    growthRatePercent: 30,
    timeToJobReadyMinMonths: 6,
    timeToJobReadyMaxMonths: 12,
    iconKey: 'shield',
    colorTone: 'red',
    tags: ['cybersecurity', 'security', 'network', 'infosec'],
    active: true,
  },
  {
    _id: careerIds.productManager,
    slug: 'product-manager',
    title: 'Product Manager',
    domainId: domainIds.business,
    summary: 'Lead teams to build products people actually want.',
    description:
      'Product Managers define product strategy, prioritize what gets built, and align designers, engineers, and stakeholders around a shared roadmap.',
    requiredSkills: [
      { skillId: skillIds.productStrategy, importance: 'critical' },
      { skillId: skillIds.communication, importance: 'important' },
      { skillId: skillIds.leadership, importance: 'important' },
      { skillId: skillIds.businessAnalysis, importance: 'important' },
    ],
    responsibilities: [
      'Define product strategy and prioritize the roadmap.',
      'Gather requirements from users and stakeholders.',
      'Align design and engineering teams around shared goals.',
    ],
    toolsToLearn: ['Jira', 'Notion', 'Figma', 'Amplitude'],
    traits: ['people', 'communication'],
    expectedSalary: { min: 70_000, max: 135_000, currency: 'USD' },
    demand: 'high',
    growthRatePercent: 19,
    timeToJobReadyMinMonths: 8,
    timeToJobReadyMaxMonths: 14,
    iconKey: 'target',
    colorTone: 'teal',
    tags: ['product', 'management', 'strategy', 'leadership'],
    active: true,
  },
]