import { userIds } from './ids.js'
export const helpSeed = [
  { title: 'Building your Career Passport', slug: 'building-your-career-passport', summary: 'How to complete onboarding and keep your profile useful for recommendations.', body: 'Complete your stage, interests, goals, education, skills, and experience. You can return to Profile and update these fields at any time.', category: 'Getting started', sortOrder: 1, published: true, createdBy: userIds.superAdmin },
  { title: 'Understanding match scores', slug: 'understanding-match-scores', summary: 'What PathSeeker uses when explaining career matches.', body: 'Match scores are calculated from the profile signals and career records supported by the application. Review the reasons shown with each recommendation rather than treating a score as a guarantee.', category: 'Recommendations', sortOrder: 2, published: true, createdBy: userIds.superAdmin },
  { title: 'Managing saved careers and notes', slug: 'managing-saved-careers-and-notes', summary: 'Save careers and keep notes that persist with your account.', body: 'Use the bookmark action on a career or supported content item. Saved notes are stored on the server and remain available after refresh and on another signed-in device.', category: 'Personalization', sortOrder: 3, published: true, createdBy: userIds.superAdmin },
  { title: 'Quiz privacy and personalization', slug: 'quiz-privacy-and-personalization', summary: 'Understand how quiz attempts and personalization settings work.', body: 'Quiz attempts are stored against your account so you can resume and review historical results. Use your privacy and personalization settings to control supported activity-based recommendations.', category: 'Privacy', sortOrder: 4, published: true, createdBy: userIds.superAdmin },
  { title: 'Account security and data', slug: 'account-security-and-data', summary: 'Password, verification, sessions, and account controls.', body: 'Use email verification and password reset when needed. Signing out revokes the current session, while account deactivation is handled through Profile settings.', category: 'Account', sortOrder: 5, published: true, createdBy: userIds.superAdmin },
  { title: 'Using Navi voice guidance', slug: 'using-navi-voice-guidance', summary: 'How to use voice guidance and the text fallback.', body: 'Choose Ask Navi from supported screens, grant microphone permission when prompted, and use the transcript or text fallback if speech recognition is unavailable.', category: 'Navi', sortOrder: 6, published: true, createdBy: userIds.superAdmin },
]
