import Icon from '../../components/Icon'
import { useEffect, useState } from 'react'
import { apiRequest, endpoints } from '../../services/pathseekerApi'

export default function HelpCenterPage({ navigate }) {
  const [query, setQuery] = useState(''); const [articles, setArticles] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); apiRequest(`${endpoints.help}?q=${encodeURIComponent(query)}&limit=30`).then(({ data }) => setArticles(data.articles || [])).catch(err => setError(err.message || 'Could not load help content.')).finally(() => setLoading(false)) }, 200); return () => clearTimeout(timer) }, [query])
  return <div className="page-stack"><section className="help-hero"><span className="eyebrow">Help center</span><h1>How can we help?</h1><p>Search the managed PathSeeker knowledge base.</p><div><Icon name="search"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search help topics" aria-label="Search help topics"/></div></section>{error && <div className="panel form-error" role="alert">{error}</div>}{loading ? <div className="panel">Loading help articles…</div> : <section className="help-topic-grid">{articles.map(article => <button className="panel" key={article._id} onClick={() => setSelected(article)}><span className="career-icon mint"><Icon name="help"/></span><strong>{article.title}</strong><p>{article.summary}</p><small>{article.category}</small><Icon name="arrow"/></button>)}{!articles.length && <div className="panel">No help articles match that search.</div>}</section>}{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className="panel help-article-modal" role="dialog" aria-modal="true" onClick={e => e.stopPropagation()}><button className="button ghost" onClick={() => setSelected(null)}>Close</button><span className="eyebrow">{selected.category}</span><h2>{selected.title}</h2><p>{selected.summary}</p><div className="help-article-body">{selected.body}</div></article></div>}<section className="contact-strip panel"><img src="/assets/navi/navi-listening.png" alt="Navi listening"/><div><span className="eyebrow">Still need a hand?</span><h2>Talk to the PathSeeker team</h2><p>Send a message and we’ll get back to you.</p></div><button className="button primary" onClick={() => navigate('feedback')}>Contact support <Icon name="message"/></button></section></div>
}
