import Icon from '../../components/Icon'
import NaviPrompt from '../../components/user/NaviPrompt'
import { useEffect, useState } from 'react'
import { apiRequest, endpoints, mapCareer } from '../../services/pathseekerApi'

export default function RecommendationsPage({ navigate, onVoice }) {
  const [items, setItems] = useState([]); const [bookmarks, setBookmarks] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([apiRequest(endpoints.recommendations), apiRequest(endpoints.bookmarks)]).then(([recommendations, saved]) => { setItems(recommendations.data.recommendations || []); setBookmarks(saved.data.bookmarks || []) }).catch((err) => setError(err.message || 'Could not load recommendations.')).finally(() => setLoading(false)) }, [])
  const toggleSaved = async (career) => { const existing = bookmarks.find((item) => item.itemType === 'career' && item.itemId === career._id); try { if (existing) { await apiRequest(`${endpoints.bookmarks}/${existing._id}`, { method: 'DELETE' }); setBookmarks((items) => items.filter((item) => item._id !== existing._id)) } else { const { data } = await apiRequest(endpoints.bookmarks, { method: 'POST', body: JSON.stringify({ itemType: 'career', itemId: career._id }) }); setBookmarks((items) => [data.bookmark, ...items]) } } catch (err) { setError(err.message || 'Could not update bookmark.') } }
  return <div className="recommendations page-stack"><section className="results-hero"><div><span className="eyebrow"><Icon name="sparkles" size={15} /> Explainable recommendations</span><h1>Career matches built from your passport</h1><p>These matches use your saved profile skills and interests plus transparent career signals. They are guidance, not a promise.</p><button className="button soft" onClick={onVoice}><Icon name="mic" /> Hear Navi explain</button></div><div className="results-navi"><img src="/assets/navi/navi-celebrating.png" alt="Navi" /></div></section>{error && <div className="panel form-error">{error}</div>}{loading ? <div className="panel">Building your matches…</div> : <section><div className="result-list">{items.map((item, index) => { const career = mapCareer(item.career, item.match); return <article key={career._id} className="result-card"><span className="rank">{String(index + 1).padStart(2, '0')}</span><span className={`career-icon ${career.tone}`}><Icon name={career.icon} /></span><div className="result-main"><span className="match-pill">{item.match}% match</span><h3>{career.title}</h3><p>{career.summary}</p><div className="career-meta"><span><small>Salary</small><strong>{career.salary}</strong></span><span><small>Outlook</small><strong>{career.growth}</strong></span></div><div className="skill-row">{item.reasons.map((reason) => <span key={reason}>{reason}</span>)}</div></div><div className="result-actions"><button className={`save-button ${bookmarks.some((b) => b.itemType === 'career' && b.itemId === career._id) ? 'saved' : ''}`} onClick={() => toggleSaved(career)}><Icon name="bookmark" /></button><button className="button primary small" onClick={() => navigate('career-detail', career.slug)}>View career <Icon name="arrow" size={16} /></button></div></article> })}</div>{!items.length && <div className="panel">Complete your profile and quiz to improve recommendations.</div>}</section>}<NaviPrompt pose="pointing-left" title="Refine the signal, not the label" action="Retake quiz" onAction={() => navigate('quiz')}>Your results are a starting point. If they feel wrong, update your profile or retake the quiz instead of treating one score as a verdict.</NaviPrompt></div>
}
