import Icon from '../../components/Icon'
import BackButton from '../../components/common/BackButton'
import PageTitle from '../../components/common/PageTitle'
import { useEffect, useState } from 'react'
import { apiRequest, endpoints } from '../../services/pathseekerApi'

export default function SubmitStoryPage({ navigate, storyId }) {
  const editing = Boolean(storyId); const [domains, setDomains] = useState([]); const [authorName,setAuthorName]=useState(''); const [domainId,setDomainId]=useState(''); const [educationPath,setEducationPath]=useState(''); const [challenges,setChallenges]=useState(''); const [outcome,setOutcome]=useState(''); const [storyText,setStoryText]=useState(''); const [consent,setConsent]=useState(true); const [image,setImage]=useState(null); const [existingImage,setExistingImage]=useState(null); const [loading,setLoading]=useState(editing); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState(''); const [sent,setSent]=useState(false)
  useEffect(() => { Promise.all([apiRequest(endpoints.domains), editing ? apiRequest(endpoints.myStory(storyId)) : Promise.resolve({data:{story:null}})]).then(([d,s]) => { setDomains(d.data.domains || []); const story=s.data.story; if(story){setAuthorName(story.authorName||'');setDomainId(story.domainId?._id||story.domainId||'');setEducationPath(story.educationPath||'');setChallenges(story.challenges||'');setOutcome(story.outcome||'');setStoryText(story.storyText||'');setConsent(story.consent===true);setExistingImage(story.image||null)} }).catch(err=>setError(err.message||'Could not load story.')).finally(()=>setLoading(false)) }, [editing, storyId])
  const upload = async () => { if(!image) return existingImage; setUploading(true); try { const form=new FormData(); form.append('file',image); const {data}=await apiRequest(endpoints.storyUpload,{method:'POST',body:form,timeoutMs:60000}); return data.asset } finally { setUploading(false) } }
  const submit = async e => { e.preventDefault(); setSaving(true); setError(''); try { const uploaded=await upload(); const payload={authorName,domainId,educationPath,challenges,outcome,storyText,consent,image:uploaded}; if(editing){ await apiRequest(endpoints.myStory(storyId),{method:'PATCH',body:JSON.stringify(payload)}); await apiRequest(endpoints.submitMyStory(storyId),{method:'POST'}) } else { await apiRequest(endpoints.stories,{method:'POST',body:JSON.stringify(payload)}) } setSent(true) } catch(err){setError(err.message||'Could not submit your story.')} finally{setSaving(false)} }
  if(loading)return <div className="page-stack"><div className="panel">Loading story…</div></div>
  if(sent)return <div className="submission-success"><img src="/assets/navi/navi-celebrating.png" alt="Navi"/><span><Icon name="check"/></span><h1>{editing ? 'Your updated story is back with the review team.' : 'Your story is with our review team.'}</h1><p>An administrator must approve it before it becomes public.</p><button className="button primary" onClick={()=>navigate('stories')}>Back to stories</button></div>
  return <div className="page-stack"><BackButton navigate={navigate} to="stories">Back to success stories</BackButton><PageTitle eyebrow={editing ? 'Update your journey' : 'Share your journey'} title={editing ? 'Address the review feedback' : 'Your path could help someone else begin'} copy={editing ? 'Update the requested fields, then resubmit for moderation.' : 'Submissions are stored as pending until an administrator reviews them.'}/><form className="panel story-form" onSubmit={submit}><label>Your name<input required value={authorName} onChange={e=>setAuthorName(e.target.value)} maxLength={150}/></label><label>Domain<select required value={domainId} onChange={e=>setDomainId(e.target.value)}><option value="">Choose a domain</option>{domains.map(d=><option key={d._id} value={d._id}>{d.name}</option>)}</select></label><label>Educational path<textarea value={educationPath} onChange={e=>setEducationPath(e.target.value)} maxLength={1500}/></label><label>Challenges<textarea value={challenges} onChange={e=>setChallenges(e.target.value)} maxLength={2000}/></label><label>Outcome<textarea value={outcome} onChange={e=>setOutcome(e.target.value)} maxLength={1500}/></label><label>Your story<textarea required minLength={20} maxLength={5000} value={storyText} onChange={e=>setStoryText(e.target.value)}/></label><label>Optional image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setImage(e.target.files?.[0]||null)}/><small>Maximum 8 MB. The file is validated before storage.</small></label>{existingImage?.url&&!image&&<p className="form-help">Existing image retained.</p>}{error&&<p className="form-error" role="alert">{error}</p>}<label className="check-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/> I consent to PathSeeker storing and, if approved, publishing this story.</label><button className="button primary" disabled={saving||uploading} type="submit">{uploading?'Uploading image…':saving?'Saving…':editing?'Save and resubmit':'Submit for review'} <Icon name="arrow"/></button></form></div>
}
