import Icon from '../../components/Icon'
import PageHead from '../../components/admin/PageHead'
import { useEffect, useState } from 'react'
import { apiRequest, endpoints } from '../../services/pathseekerApi'

export default function ContentAdmin({ navigate }) {
 const [resources,setResources]=useState([]);const [media,setMedia]=useState([]);const [loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);return Promise.all([apiRequest(`${endpoints.admin.resources}?limit=100`),apiRequest(`${endpoints.admin.media}?limit=100`)]).then(([r,m])=>{setResources(r.data.resources||[]);setMedia(m.data.media||[])}).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[])
 const setStatus=async(type,id,status)=>{try{const endpoint=type==='resource'?endpoints.admin.resourceStatus:endpoints.admin.mediaStatus;await apiRequest(endpoint(id,status),{method:'PATCH'});load()}catch(err){alert(err.message||'Could not change publication status.')}};
 const remove=async(type,id)=>{if(!window.confirm('Delete this content record?'))return;await apiRequest(`${type==='resource'?endpoints.admin.resources:endpoints.admin.media}/${id}`,{method:'DELETE'});load()};
 return <div className="admin-stack"><PageHead eyebrow="Learning library" title="Content management" description="Live resource and multimedia records."><button className="button soft" onClick={load}><Icon name="refresh"/> Refresh</button><button className="button primary" onClick={()=>navigate('admin-content-editor')}><Icon name="plus"/> Add content</button></PageHead>{loading?<div className="panel">Loading content…</div>:<section className="panel admin-table"><table><thead><tr><th>Title</th><th>Type</th><th>Status</th><th>Usage</th><th /></tr></thead><tbody>{[...resources.map(r=>({...r,contentType:'resource'})),...media.map(m=>({...m,contentType:'media'}))].map(item=><tr key={item._id}><td>{item.title}</td><td>{item.type}</td><td>{item.status || (item.active?'published':'draft')}</td><td>{item.contentType==='resource'?`${item.downloadCount||0} downloads`:`${item.ratingCount||0} ratings`}</td><td><button className="button ghost small" onClick={()=>navigate('admin-content-editor',item._id)}>Edit</button>{item.status!=='published'&&<button className="button ghost small" onClick={()=>setStatus(item.contentType,item._id,'published')}>Publish</button>}{item.status==='published'&&<button className="button ghost small" onClick={()=>setStatus(item.contentType,item._id,'archived')}>Archive</button>}{item.status==='archived'&&<button className="button ghost small" onClick={()=>setStatus(item.contentType,item._id,'draft')}>Move to draft</button>}<button className="button ghost small" onClick={()=>remove(item.contentType,item._id)}>Delete</button></td></tr>)}</tbody></table></section>}</div>
}
