import Icon from '../../components/Icon'
import PageHead from '../../components/admin/PageHead'
import Status from '../../components/admin/Status'
import { useEffect, useState } from 'react'
import { apiRequest, endpoints } from '../../services/pathseekerApi'

const blank = () => ({ questionText: '', type: 'multiple_choice', order: 0, timeLimitSeconds: 0, active: true, options: [{ key: 'a', label: '', domainId: '' }, { key: 'b', label: '', domainId: '' }, { key: 'c', label: '', domainId: '' }, { key: 'd', label: '', domainId: '' }] })

export default function QuizAdmin() {
  const [questions, setQuestions] = useState([]); const [domains, setDomains] = useState([]); const [versions, setVersions] = useState([])
  const [loading, setLoading] = useState(true); const [editor, setEditor] = useState(null); const [preview, setPreview] = useState(null); const [error, setError] = useState(''); const [publishing, setPublishing] = useState(false)
  const load = async () => { setLoading(true); setError(''); try { const [q, d, v] = await Promise.all([apiRequest(endpoints.admin.quizQuestions), apiRequest(endpoints.domains), apiRequest(endpoints.admin.quizVersions)]); setQuestions(q.data.questions || []); setDomains(d.data.domains || []); setVersions(v.data.versions || []) } catch (err) { setError(err.message || 'Could not load quiz builder data.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const save = async () => { setError(''); const options = editor.options.map(o => ({ key: o.key, label: o.label, domainWeights: o.domainId ? [{ domainId: o.domainId, weight: 1 }] : [] })); if (!editor.questionText.trim() || options.some(o => !o.label.trim())) { setError('Question text and all option labels are required.'); return } try { const payload = { questionText: editor.questionText, type: editor.type, order: Number(editor.order) || 0, timeLimitSeconds: Number(editor.timeLimitSeconds) || 0, active: editor.active, options }; if (editor._id) await apiRequest(`${endpoints.admin.quizQuestions}/${editor._id}`, { method: 'PATCH', body: JSON.stringify(payload) }); else await apiRequest(endpoints.admin.quizQuestions, { method: 'POST', body: JSON.stringify(payload) }); setEditor(null); await load() } catch (err) { setError(err.message || 'Could not save the quiz question.') } }
  const remove = async (id) => { if (!window.confirm('Delete this quiz question? Historical attempts keep their snapshots.')) return; try { await apiRequest(`${endpoints.admin.quizQuestions}/${id}`, { method: 'DELETE' }); await load() } catch (err) { setError(err.message || 'Could not delete the question.') } }
  const move = async (index, direction) => { const next = [...questions]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setQuestions(next); try { await apiRequest(endpoints.admin.quizOrder, { method: 'PATCH', body: JSON.stringify({ questionIds: next.map(q => q._id) }) }); await load() } catch (err) { setError(err.message || 'Could not reorder questions.'); await load() } }
  const publish = async () => { setPublishing(true); setError(''); try { await apiRequest(endpoints.admin.quizPublish, { method: 'POST', body: JSON.stringify({ title: 'Interest Quiz' }) }); await load() } catch (err) { setError(err.message || 'Could not publish the quiz version.') } finally { setPublishing(false) } }
  const openPreview = async () => { try { const { data } = await apiRequest(endpoints.admin.quizPreview); setPreview(data.questions || []) } catch (err) { setError(err.message || 'Could not load preview.') } }

  return <div className="admin-stack">
    <PageHead eyebrow="Assessment engine" title="Quiz builder" description="Build the draft question set, validate scoring, preview it, reorder questions, and publish immutable versions."><button className="button soft" onClick={load}><Icon name="refresh"/> Refresh</button><button className="button soft" onClick={openPreview}><Icon name="eye"/> Preview</button><button className="button primary" disabled={publishing} onClick={publish}>{publishing ? 'Publishing…' : 'Publish new version'} <Icon name="check"/></button><button className="button ghost" onClick={() => setEditor(blank())}><Icon name="plus"/> Add question</button></PageHead>
    {error && <div className="panel form-error" role="alert">{error}</div>}
    {loading ? <div className="panel">Loading quiz builder…</div> : <>
      <section className="panel"><h2>Draft question set</h2><p className="form-help">Published versions are immutable snapshots. Editing questions only changes the next version.</p><div className="question-list">{questions.map((q, index) => <article key={q._id}><span>{index + 1}</span><div><strong>{q.questionText}</strong><small>{q.type} · question v{q.version || 1} · {q.options.length} options</small></div><Status tone={q.active ? 'success' : 'draft'}>{q.active ? 'Included' : 'Excluded'}</Status><button className="button ghost small" disabled={index === 0} onClick={() => move(index, -1)} aria-label="Move question up">↑</button><button className="button ghost small" disabled={index === questions.length - 1} onClick={() => move(index, 1)} aria-label="Move question down">↓</button><button className="button ghost small" onClick={() => setEditor({ ...q, timeLimitSeconds: q.timeLimitSeconds || 0, options: q.options.map(o => ({ key: o.key, label: o.label, domainId: o.domainWeights?.[0]?.domainId?._id || o.domainWeights?.[0]?.domainId || '' })) })}>Edit</button><button className="button ghost small" onClick={() => remove(q._id)}>Delete</button></article>)}</div></section>
      <section className="panel"><div className="section-head"><div><span className="eyebrow">Version history</span><h2>Published quiz versions</h2></div></div>{versions.length ? <div className="question-list">{versions.map(v => <article key={v._id}><span>v{v.version}</span><div><strong>{v.title}</strong><small>{v.questions?.length || 0} questions · {v.scoringVersion}</small></div><Status tone={v.status === 'published' ? 'success' : 'draft'}>{v.status}</Status><small>{v.publishedAt ? new Date(v.publishedAt).toLocaleString() : 'Not published'}</small></article>)}</div> : <p>No published quiz version yet. The user quiz will use the legacy active-question fallback until the first version is published.</p>}</section>
    </>}
    {editor && <section className="panel admin-editor-form"><h2>{editor._id ? 'Edit question' : 'New question'}</h2>{error && <p className="form-error">{error}</p>}<div className="form-grid"><label className="full">Question<textarea value={editor.questionText} onChange={e => setEditor({ ...editor, questionText: e.target.value })}/></label><label>Type<select value={editor.type} onChange={e => setEditor({ ...editor, type: e.target.value })}><option value="multiple_choice">Multiple choice</option><option value="likert">Likert</option><option value="slider">Slider</option></select></label><label>Order<input type="number" value={editor.order} onChange={e => setEditor({ ...editor, order: e.target.value })}/></label><label>Time limit (seconds)<input type="number" min="0" max="3600" value={editor.timeLimitSeconds || 0} onChange={e => setEditor({ ...editor, timeLimitSeconds: e.target.value })}/></label></div><h3>Options / scoring signal</h3>{editor.options.map((option, index) => <div className="form-grid" key={option.key}><label>Option {option.key.toUpperCase()}<input value={option.label} onChange={e => setEditor({ ...editor, options: editor.options.map((o, i) => i === index ? { ...o, label: e.target.value } : o) })}/></label><label>Domain<select value={option.domainId || ''} onChange={e => setEditor({ ...editor, options: editor.options.map((o, i) => i === index ? { ...o, domainId: e.target.value } : o) })}><option value="">No scoring signal</option>{domains.map(d => <option key={d._id} value={d._id}>{d.name}</option>)}</select></label></div>)}<label className="check-row"><input type="checkbox" checked={editor.active} onChange={e => setEditor({ ...editor, active: e.target.checked })}/> Include in next published version</label><div className="form-actions"><button className="button ghost" onClick={() => setEditor(null)}>Cancel</button><button className="button primary" onClick={save}>Save question</button></div></section>}
    {preview && <div className="modal-backdrop" role="presentation" onClick={() => setPreview(null)}><section className="panel" role="dialog" aria-modal="true" onClick={e => e.stopPropagation()}><div className="section-head"><div><span className="eyebrow">Draft preview</span><h2>What users will see</h2></div><button className="button ghost" onClick={() => setPreview(null)}>Close</button></div><div className="quiz-options">{preview.map((q, i) => <article className="panel" key={q._id}><small>Question {i + 1} · {q.type}</small><h3>{q.questionText}</h3>{q.options.map(o => <p key={o.key}><strong>{o.key.toUpperCase()}.</strong> {o.label}</p>)}</article>)}</div></section></div>}
  </div>
}
