import { useState } from 'react'
import Icon from '../components/Icon'

const Head = ({ eyebrow, title, copy, children }) => <div className="admin-page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{children}</div>
const Field = ({ label, children }) => <label className="admin-field"><span>{label}</span>{children}</label>

export function AdminUserEditor({ navigate }) {
  const [saved, setSaved] = useState(false)
  return <div className="admin-stack"><Head eyebrow="Community · User record" title="Alex Morgan" copy="Review profile details, engagement, and account access."><button className="button ghost" onClick={() => navigate('admin-users')}>Cancel</button><button className="button primary" onClick={() => setSaved(true)}>Save changes</button></Head>{saved && <div className="admin-toast"><Icon name="check" /> User changes saved to the frontend fixture.</div>}<div className="admin-editor-layout"><section className="panel admin-editor-form"><div className="editor-section"><h2>Personal details</h2><div className="form-grid"><Field label="Full name"><input defaultValue="Alex Morgan" /></Field><Field label="Email"><input defaultValue="alex@example.com" /></Field><Field label="Stage"><select defaultValue="Student"><option>Student</option><option>Graduate</option><option>Professional</option></select></Field><Field label="Location"><input defaultValue="Karachi, Pakistan" /></Field></div></div><div className="editor-section"><h2>Account access</h2><div className="form-grid"><Field label="Status"><select defaultValue="Active"><option>Active</option><option>Inactive</option><option>Suspended</option></select></Field><Field label="Role"><select defaultValue="User"><option>User</option><option>Administrator</option></select></Field></div><label className="toggle-row"><span><strong>Email verified</strong><small>User completed email verification.</small></span><input type="checkbox" defaultChecked /><i /></label></div><div className="danger-zone"><h3>Danger zone</h3><p>Suspend access or remove the user after a confirmation step.</p><button className="button ghost">Suspend account</button></div></section><aside className="panel admin-profile-summary"><span className="avatar">AM</span><h3>Alex Morgan</h3><p>Student · Explorer plan</p><dl><div><dt>Quiz status</dt><dd>Completed</dd></div><div><dt>Saved careers</dt><dd>3</dd></div><div><dt>Last active</dt><dd>2 min ago</dd></div><div><dt>Member since</dt><dd>Mar 3, 2026</dd></div></dl></aside></div></div>
}

export function AdminCareerEditor({ navigate }) {
  const [tab, setTab] = useState('Overview')
  return <div className="admin-stack"><Head eyebrow="Career Bank · Editor" title="UX Designer" copy="Maintain the public profile, matching signals, and learning roadmap."><button className="button ghost" onClick={() => navigate('admin-careers')}>Cancel</button><button className="button soft">Save draft</button><button className="button primary">Publish changes</button></Head><div className="editor-tabs">{['Overview','Salary & demand','Skills','Roadmap','Matching'].map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><section className="panel admin-editor-form">{tab === 'Overview' && <div className="editor-section"><h2>Career overview</h2><div className="form-grid"><Field label="Career title"><input defaultValue="UX Designer" /></Field><Field label="Domain"><select defaultValue="Design & Technology"><option>Design & Technology</option><option>Data & Business</option></select></Field><Field label="Short summary"><textarea defaultValue="Shape intuitive digital products by understanding people and turning their needs into thoughtful experiences." /></Field><Field label="Publishing status"><select defaultValue="Published"><option>Published</option><option>Draft</option></select></Field></div></div>}{tab === 'Salary & demand' && <div className="editor-section"><h2>Market outlook</h2><div className="form-grid"><Field label="Minimum salary"><input type="number" defaultValue="72000" /></Field><Field label="Maximum salary"><input type="number" defaultValue="118000" /></Field><Field label="Projected growth"><input defaultValue="13%" /></Field><Field label="Demand label"><select defaultValue="High demand"><option>High demand</option><option>Very high</option><option>Growing</option></select></Field></div></div>}{tab === 'Skills' && <div className="editor-section"><h2>Core skills</h2><div className="tag-editor">{['User research','Figma','Prototyping','Empathy'].map((skill) => <span key={skill}>{skill}<button>×</button></span>)}<button><Icon name="plus" /> Add skill</button></div></div>}{tab === 'Roadmap' && <div className="editor-section"><h2>Learning roadmap</h2>{['Understand the foundations','Practice research and prototyping','Build two portfolio projects','Prepare and start applying'].map((step, index) => <div className="admin-roadmap-row" key={step}><span>{index + 1}</span><input defaultValue={step} /><input defaultValue={['2 weeks','6–8 weeks','8–12 weeks','4 weeks'][index]} /><button><Icon name="more" /></button></div>)}</div>}{tab === 'Matching' && <div className="editor-section"><h2>Matching signals</h2><p>Weights will be stored as numeric fields in the career document.</p>{['Creative problem-solving','Empathy','Structured thinking','Collaboration'].map((signal, index) => <label className="range-row" key={signal}><span>{signal}</span><input type="range" defaultValue={90 - index * 8} /><strong>{90 - index * 8}%</strong></label>)}</div>}</section></div>
}

export function AdminContentEditor({ navigate }) {
  const [format, setFormat] = useState('Video')
  return <div className="admin-stack"><Head eyebrow="Learning library · Editor" title="Add content" copy="Create a frontend record ready for the future content API and media storage."><button className="button ghost" onClick={() => navigate('admin-content')}>Cancel</button><button className="button soft">Save draft</button><button className="button primary">Publish content</button></Head><div className="admin-editor-layout"><section className="panel admin-editor-form"><div className="editor-section"><h2>Content details</h2><div className="form-grid"><Field label="Title"><input defaultValue="Design interviews that uncover real needs" /></Field><Field label="Format"><select value={format} onChange={(event) => setFormat(event.target.value)}><option>Video</option><option>Podcast</option><option>Course</option><option>Document</option></select></Field><Field label="Description"><textarea defaultValue="A practical guide to planning and running a useful research interview." /></Field><Field label="Author"><input defaultValue="Maya Chen" /></Field></div></div><div className="editor-section"><h2>{format === 'Document' ? 'Document file' : 'Media source'}</h2><div className="upload-zone"><Icon name={format === 'Document' ? 'file' : 'video'} size={30} /><strong>Drop a file here or browse</strong><small>Frontend preview only · the backend can later use S3, Cloudinary, or GridFS metadata.</small><button className="button soft">Choose file</button></div></div><div className="editor-section"><h2>Discovery</h2><div className="tag-editor">{['UX Design','Beginner','Skill-building'].map((tag) => <span key={tag}>{tag}<button>×</button></span>)}<button><Icon name="plus" /> Add tag</button></div></div></section><aside className="panel publish-checklist"><span className="eyebrow">Before publishing</span><h3>Content checklist</h3>{['Title and description','Accessible transcript','Career tags','Preview image','Usage rights'].map((item, index) => <p key={item}><Icon name={index < 3 ? 'check' : 'clock'} />{item}</p>)}</aside></div></div>
}

export function AdminStoryReview({ navigate }) {
  const [status, setStatus] = useState('Pending review')
  return <div className="admin-stack"><Head eyebrow="Success stories · Review" title="Aisha Rahman’s journey" copy="Review the submitted story, leave editorial notes, and prepare it for publishing."><button className="button ghost" onClick={() => navigate('admin-stories')}>Back</button><button className="button soft" onClick={() => setStatus('Needs edits')}>Request edits</button><button className="button primary" onClick={() => setStatus('Published')}>Approve & publish</button></Head><div className="review-status"><Icon name={status === 'Published' ? 'check' : 'clock'} /> Current status: <strong>{status}</strong></div><div className="admin-review-layout"><section className="panel review-copy"><span className="eyebrow">Submitted story</span><h2>How psychology led me to UX design</h2><blockquote>“I thought changing direction meant starting over. It turned out I already had the hardest skill to teach: understanding people.”</blockquote><h3>The challenge</h3><p>I knew I wanted people-centered work, but I could not see how my psychology degree connected to technology.</p><h3>The turning point</h3><p>I tested UX research with one small campus project and realized my psychology training was an advantage.</p><h3>The outcome</h3><p>Five months later, I accepted my first junior UX role.</p></section><aside className="panel review-panel"><span className="avatar">AR</span><h3>Aisha Rahman</h3><p>aisha@example.com</p><Field label="Internal editorial note"><textarea defaultValue="Strong story. Ask for one portfolio image and confirm company name before featuring." /></Field><label className="check-row"><input type="checkbox" defaultChecked /> Consent confirmed</label><label className="check-row"><input type="checkbox" /> Feature on homepage</label><button className="button soft full">Save internal note</button></aside></div></div>
}

export function AdminFeedbackAnalytics() {
  const sentiments = [['Positive',62,'mint'],['Neutral',25,'blue'],['Negative',13,'rose']]
  return <div className="admin-stack"><Head eyebrow="Voice of the user" title="Feedback analytics" copy="Understand sentiment, topics, and response trends across submitted feedback."><button className="button soft"><Icon name="download" /> Export analytics</button></Head><section className="admin-kpis"><article><div><span className="career-icon mint"><Icon name="message" /></span></div><strong>428</strong><p>Responses this month</p><small>+18% from July</small></article><article><div><span className="career-icon amber"><Icon name="clock" /></span></div><strong>6.2h</strong><p>Average response time</p><small>1.4h faster</small></article><article><div><span className="career-icon blue"><Icon name="check" /></span></div><strong>91%</strong><p>Resolution rate</p><small>Within 48 hours</small></article><article><div><span className="career-icon lavender"><Icon name="star" /></span></div><strong>4.3</strong><p>Experience rating</p><small>From 312 ratings</small></article></section><div className="analytics-detail-grid"><section className="panel sentiment-panel"><span className="eyebrow">Sentiment summary</span><h2>Most feedback is positive</h2><div className="sentiment-bar">{sentiments.map(([label,value,tone]) => <i className={tone} style={{ width: `${value}%` }} key={label} />)}</div>{sentiments.map(([label,value,tone]) => <p key={label}><i className={tone} /><span>{label}</span><strong>{value}%</strong></p>)}</section><section className="panel response-panel"><span className="eyebrow">Response types</span><h2>What people are sending</h2>{[['Ideas',38,'sparkles'],['Problems',27,'settings'],['Content questions',21,'book'],['Praise',14,'heart']].map(([label,value,icon]) => <div key={label}><span><Icon name={icon} />{label}</span><div><i style={{ width: `${value * 2}%` }} /></div><strong>{value}%</strong></div>)}</section></div><section className="panel topic-table"><div className="admin-section-head"><div><span className="eyebrow">Emerging topics</span><h2>What needs attention</h2></div></div>{[['Career comparison','46 mentions','High opportunity'],['Quiz explanations','31 mentions','Content improvement'],['Podcast playback','18 mentions','Technical issue'],['Mobile navigation','12 mentions','Usability']].map((row) => <div key={row[0]}>{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</section></div>
}

export function AdminSettingsPage() {
  const [section, setSection] = useState('Workspace')
  return <div className="admin-stack"><Head eyebrow="Administration" title="Settings" copy="Configure the PathSeeker workspace, team roles, and notification defaults."><button className="button primary">Save settings</button></Head><div className="admin-settings-layout"><aside className="panel settings-nav">{['Workspace','Team & roles','Notifications','Security','Data & privacy'].map((item) => <button className={section === item ? 'active' : ''} onClick={() => setSection(item)} key={item}><Icon name={item === 'Workspace' ? 'globe' : item === 'Team & roles' ? 'users' : item === 'Notifications' ? 'bell' : item === 'Security' ? 'shield' : 'file'} />{item}<Icon name="chevron" /></button>)}</aside><section className="panel admin-editor-form"><span className="eyebrow">{section}</span><h2>{section} settings</h2>{section === 'Workspace' && <div className="form-grid"><Field label="Workspace name"><input defaultValue="PathSeeker HQ" /></Field><Field label="Support email"><input defaultValue="support@pathseeker.app" /></Field><Field label="Default timezone"><select defaultValue="Asia/Karachi"><option>Asia/Karachi</option><option>UTC</option></select></Field><Field label="Default language"><select defaultValue="English"><option>English</option><option>Urdu</option></select></Field></div>}{section === 'Team & roles' && <div className="settings-list">{[['Sarah Malik','Super admin'],['Omar Shah','Content editor'],['Mina Raza','Support manager']].map(([name,role]) => <div key={name}><span className="avatar small">{name.split(' ').map((x) => x[0]).join('')}</span><p><strong>{name}</strong><small>{role}</small></p><button><Icon name="more" /></button></div>)}<button className="button soft"><Icon name="plus" /> Invite teammate</button></div>}{section === 'Notifications' && ['New feedback','Story submissions','Content awaiting review','Weekly analytics digest'].map((item, index) => <label className="toggle-row" key={item}><span><strong>{item}</strong><small>Notify workspace administrators.</small></span><input type="checkbox" defaultChecked={index < 3} /><i /></label>)}{section === 'Security' && <><label className="toggle-row"><span><strong>Require two-factor authentication</strong><small>Applies to every administrator.</small></span><input type="checkbox" defaultChecked /><i /></label><label className="toggle-row"><span><strong>Session timeout</strong><small>Sign out inactive administrators after 30 minutes.</small></span><input type="checkbox" defaultChecked /><i /></label></>}{section === 'Data & privacy' && <div className="settings-list"><button><Icon name="download" /><p><strong>Export workspace data</strong><small>Create a portable archive.</small></p><Icon name="chevron" /></button><button><Icon name="shield" /><p><strong>Retention settings</strong><small>Control how long operational data is kept.</small></p><Icon name="chevron" /></button></div>}</section></div></div>
}

export function AdminHelpPage() {
  return <div className="admin-stack"><Head eyebrow="PathSeeker support" title="Admin help center" copy="Guides for managing users, careers, content, quizzes, and moderation." /><section className="admin-help-search panel"><Icon name="search" /><input placeholder="Search administrator guides" /><kbd>⌘ K</kbd></section><section className="admin-help-grid">{[['users','User access','Manage invitations, roles, and suspended accounts.'],['briefcase','Career profiles','Create accurate career data and publishing workflows.'],['library','Content library','Upload media, documents, tags, and transcripts.'],['sparkles','Quiz builder','Edit signals, answers, scoring, and publishing.'],['message','Moderation','Review stories and resolve user feedback.'],['shield','Security','Understand sessions, permissions, and data controls.']].map(([icon,title,copy]) => <button className="panel" key={title}><span className="career-icon mint"><Icon name={icon} /></span><h3>{title}</h3><p>{copy}</p><Icon name="arrow" /></button>)}</section><section className="contact-strip panel"><div><span className="eyebrow">Technical support</span><h2>Need help with the workspace?</h2><p>Contact the project team with screenshots and the affected account or content ID.</p></div><button className="button primary">Contact support</button></section></div>
}
