import { useMemo, useState } from 'react'
import Icon from '../components/Icon'
import { careers, resources } from '../data'
import { frontendFixtures } from '../services/pathseekerApi'

const PageTitle = ({ eyebrow, title, copy, actions }) => <section className="extended-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{actions && <div>{actions}</div>}</section>
const Back = ({ navigate, to, children }) => <button className="back-link" onClick={() => navigate(to)}><Icon name="arrowLeft" /> {children}</button>

export function NotificationsPage() {
  const [items, setItems] = useState(frontendFixtures.notifications)
  const [filter, setFilter] = useState('All')
  const shown = filter === 'Unread' ? items.filter((item) => !item.read) : items
  return <div className="page-stack"><PageTitle eyebrow="Inbox" title="Notifications" copy="Updates about your matches, learning, saved paths, and account." actions={<button className="button soft" onClick={() => setItems(items.map((item) => ({ ...item, read: true })))}><Icon name="check" /> Mark all read</button>} /><div className="tab-row"><button className={filter === 'All' ? 'active' : ''} onClick={() => setFilter('All')}>All <span>{items.length}</span></button><button className={filter === 'Unread' ? 'active' : ''} onClick={() => setFilter('Unread')}>Unread <span>{items.filter((item) => !item.read).length}</span></button></div><section className="notification-list panel">{shown.map((item) => <button key={item._id} className={!item.read ? 'unread' : ''} onClick={() => setItems(items.map((entry) => entry._id === item._id ? { ...entry, read: true } : entry))}><span className="notification-kind"><Icon name={item.icon} /></span><span><strong>{item.title}</strong><p>{item.body}</p><small>{item.time}</small></span>{!item.read && <i />}</button>)}</section></div>
}

export function QuizHistoryPage({ navigate }) {
  return <div className="page-stack"><PageTitle eyebrow="Your growth" title="Quiz history" copy="See how your interests and strongest career signals have changed over time." actions={<button className="button primary" onClick={() => navigate('quiz')}>Retake quiz <Icon name="arrow" /></button>} /><section className="history-summary"><article className="panel"><Icon name="sparkles" /><span><small>Attempts</small><strong>3 completed</strong></span></article><article className="panel"><Icon name="trend" /><span><small>Current top match</small><strong>94% UX Designer</strong></span></article><article className="panel"><Icon name="calendar" /><span><small>Next refresh</small><strong>Recommended in 30 days</strong></span></article></section><section className="attempt-list panel">{frontendFixtures.quizAttempts.map((attempt, index) => <article key={attempt._id}><span className={`attempt-marker ${index === 0 ? 'current' : ''}`}><Icon name={index === 0 ? 'sparkles' : 'check'} /></span><div><small>{new Date(attempt.completedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</small><h3>{attempt.archetype}</h3><p>Top match: <strong>{attempt.topCareer}</strong> · {attempt.score}% alignment</p></div><button className="button soft small" onClick={() => navigate('quiz-result')}>View results <Icon name="arrow" /></button></article>)}</section></div>
}

export function QuizResultDetailPage({ navigate }) {
  const signals = [['Empathy', 92], ['Structured thinking', 88], ['Creative problem-solving', 86], ['Collaboration', 79]]
  return <div className="page-stack"><Back navigate={navigate} to="quiz-history">Back to quiz history</Back><section className="result-detail-hero"><div><span className="eyebrow">Completed August 24, 2026</span><h1>Thoughtful Builder</h1><p>You turn human needs into practical, well-structured solutions. Your strongest results sit where creativity, analysis, and collaboration overlap.</p><div className="trait-row"><span><Icon name="heart" /> Empathetic</span><span><Icon name="chart" /> Analytical</span><span><Icon name="pen" /> Creative</span></div></div><img src="/assets/navi/navi-celebrating.png" alt="Navi celebrating" /></section><div className="result-detail-grid"><section className="panel signal-card"><span className="eyebrow">Signal breakdown</span><h2>What shaped these results</h2>{signals.map(([label, score]) => <div key={label}><span><strong>{label}</strong><small>{score}%</small></span><div><i style={{ width: `${score}%` }} /></div></div>)}</section><section className="panel answer-summary"><span className="eyebrow">Your answers</span><h2>Patterns Navi noticed</h2>{['You prefer improving real experiences over abstract exercises.', 'You enjoy finding structure inside messy information.', 'You value collaborative teams with room for focused work.'].map((copy, index) => <p key={copy}><span>0{index + 1}</span>{copy}</p>)}</section></div><section><div className="section-head"><div><span className="eyebrow">Your strongest options</span><h2>Top careers from this attempt</h2></div><button onClick={() => navigate('compare')}>Compare top careers <Icon name="arrow" /></button></div><div className="career-grid">{careers.slice(0, 3).map((career) => <article className="career-card" key={career.id}><span className={`career-icon ${career.tone}`}><Icon name={career.icon} /></span><span className="match-pill">{career.match}% match</span><h3>{career.title}</h3><p>{career.summary}</p><button className="card-link" onClick={() => navigate('career-detail', career.id)}>View career <Icon name="arrow" /></button></article>)}</div></section></div>
}

export function RecentlyViewedPage({ navigate }) {
  const [filter, setFilter] = useState('All')
  const items = filter === 'All' ? frontendFixtures.recentItems : frontendFixtures.recentItems.filter((item) => item.type === filter)
  return <div className="page-stack"><PageTitle eyebrow="Pick up where you left off" title="Recently viewed" copy="Your recent careers, learning resources, documents, and stories in one place." /><div className="filter-chips recent-filters">{['All', 'Career', 'Video', 'Story', 'Document'].map((item) => <button className={filter === item ? 'active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><section className="recent-grid">{items.map((item) => <button className="panel" key={item._id} onClick={() => navigate(...item.target)}><span className={`career-icon ${item.tone}`}><Icon name={item.icon} /></span><span><small>{item.type}</small><strong>{item.title}</strong><p>{item.meta}</p></span><Icon name="arrow" /></button>)}</section><div className="privacy-note panel"><Icon name="clock" /><p><strong>History stays private</strong><small>You can clear individual items now; full history controls will connect to your account settings.</small></p><button>Clear history</button></div></div>
}

export function CompareCareersPage({ navigate }) {
  const [ids, setIds] = useState(['ux-designer', 'data-analyst', 'product-manager'])
  const selected = ids.map((id) => careers.find((career) => career.id === id)).filter(Boolean)
  const update = (index, id) => setIds(ids.map((value, i) => i === index ? id : value))
  const rows = [
    ['Match', (career) => `${career.match}%`], ['Typical salary', (career) => career.salary], ['Projected growth', (career) => career.growth], ['Demand', (career) => career.demand], ['Time to job-ready', (_, index) => ['6–12 months', '4–9 months', '8–14 months'][index]], ['Best-fit skill', (career) => career.skills[0]],
  ]
  return <div className="page-stack"><PageTitle eyebrow="Career comparison" title="See the tradeoffs clearly" copy="Compare the fit, opportunity, preparation, and day-to-day shape of your saved careers." actions={<button className="button soft"><Icon name="download" /> Export comparison</button>} /><section className="compare-table panel"><div className="compare-head"><span>Compare</span>{selected.map((career, index) => <div key={`${career.id}-${index}`}><span className={`career-icon ${career.tone}`}><Icon name={career.icon} /></span><select value={career.id} onChange={(event) => update(index, event.target.value)}>{careers.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select><button onClick={() => navigate('career-detail', career.id)}>View profile</button></div>)}</div>{rows.map(([label, value]) => <div className="compare-row" key={label}><strong>{label}</strong>{selected.map((career, index) => <span key={`${career.id}-${label}`}>{value(career, index)}</span>)}</div>)}<div className="compare-row skills"><strong>Core skills</strong>{selected.map((career) => <span key={`${career.id}-skills`}>{career.skills.slice(0, 3).map((skill) => <em key={skill}>{skill}</em>)}</span>)}</div></section><section className="comparison-note"><img src="/assets/navi/navi-explaining.png" alt="Navi explaining" /><div><span className="eyebrow">Navi’s take</span><h2>UX Designer is your closest overall fit</h2><p>Data Analyst offers faster growth, while Product Manager has the highest salary ceiling. Your strongest personal alignment remains UX because it combines empathy and creative problem-solving.</p></div></section></div>
}

export function SavedFiltersPage({ navigate }) {
  const [filters, setFilters] = useState(frontendFixtures.savedFilters)
  const [editing, setEditing] = useState(null)
  return <div className="page-stack"><PageTitle eyebrow="Career Bank" title="Saved searches and filters" copy="Return to useful searches quickly and optionally receive alerts when new careers match." actions={<button className="button primary" onClick={() => setEditing({ _id: 'new', name: '', domains: ['Design'], salaryMin: 50000, demand: 'Any', alerts: false })}><Icon name="plus" /> New saved filter</button>} /><section className="saved-filter-grid">{filters.map((filter) => <article className="panel" key={filter._id}><div><span className="filter-icon"><Icon name="filter" /></span><button><Icon name="more" /></button></div><h3>{filter.name}</h3><p>{filter.domains.join(' + ')} · ${filter.salaryMin.toLocaleString()}+ · {filter.demand} demand</p><span className={`alert-pill ${filter.alerts ? 'on' : ''}`}><Icon name="bell" /> Alerts {filter.alerts ? 'on' : 'off'}</span><div><button className="button soft small" onClick={() => navigate('careers')}>Apply filter</button><button className="button ghost small" onClick={() => setEditing(filter)}>Edit</button></div></article>)}</section>{editing && <div className="inline-editor panel"><div><span className="eyebrow">{editing._id === 'new' ? 'New filter' : 'Edit filter'}</span><h2>Filter preferences</h2></div><form onSubmit={(event) => { event.preventDefault(); if (editing._id === 'new') setFilters([...filters, { ...editing, _id: `filter_0${filters.length + 1}`, name: editing.name || 'My saved search' }]); else setFilters(filters.map((filter) => filter._id === editing._id ? editing : filter)); setEditing(null) }}><label>Filter name<input value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><label>Minimum salary<input type="number" value={editing.salaryMin} onChange={(event) => setEditing({ ...editing, salaryMin: Number(event.target.value) })} /></label><label>Demand<select value={editing.demand} onChange={(event) => setEditing({ ...editing, demand: event.target.value })}><option>Any</option><option>High</option><option>Very high</option></select></label><label className="check-row"><input type="checkbox" checked={editing.alerts} onChange={(event) => setEditing({ ...editing, alerts: event.target.checked })} /> Email me when new careers match</label><div><button className="button ghost" type="button" onClick={() => setEditing(null)}>Cancel</button><button className="button primary" type="submit">Save filter</button></div></form></div>}</div>
}

export function MediaDetailPage({ navigate }) {
  const [playing, setPlaying] = useState(false)
  const [transcript, setTranscript] = useState(true)
  const [rating, setRating] = useState(4)
  return <div className="page-stack"><Back navigate={navigate} to="resources">Back to resources</Back><div className="media-layout"><main><section className="media-player"><div className="media-stage"><span className="career-icon blue"><Icon name="chart" size={38} /></span><div><small>Expert story</small><strong>A day in the life of a data analyst</strong></div><button className="media-play" onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pause' : 'Play'}><Icon name={playing ? 'pause' : 'play'} size={32} /></button></div><div className="media-controls"><button onClick={() => setPlaying(!playing)}><Icon name={playing ? 'pause' : 'play'} /></button><span>03:18</span><div><i style={{ width: '28%' }} /></div><span>12:04</span><button>1×</button><button><Icon name="more" /></button></div></section><section className="media-copy"><span className="eyebrow">Video · Data & business</span><h1>A day in the life of a data analyst</h1><p>Follow Sam through a real project—from cleaning messy information to presenting one clear recommendation.</p><div className="teacher"><span>SW</span><p><strong>Sam Wilson</strong><small>Senior Data Analyst · Northstar</small></p></div></section><section className="panel transcript-card"><div><div><span className="eyebrow">Accessibility</span><h2>Transcript</h2></div><button className="button soft small" onClick={() => setTranscript(!transcript)}>{transcript ? 'Hide' : 'Show'} transcript</button></div>{transcript && <div className="transcript-lines"><p><time>00:00</time><span><strong>Sam:</strong> Most days start with a question, not a spreadsheet. Today our product team wants to understand why new users stop during setup.</span></p><p className="active"><time>03:18</time><span><strong>Sam:</strong> Cleaning data is less glamorous than the chart, but it is where careful thinking matters most.</span></p><p><time>05:46</time><span><strong>Sam:</strong> The goal is not to show everything you found. It is to help someone make a better decision.</span></p></div>}</section></main><aside><section className="panel rating-card"><span className="eyebrow">Was this useful?</span><h3>Rate this resource</h3><div>{[1,2,3,4,5].map((star) => <button className={star <= rating ? 'active' : ''} key={star} onClick={() => setRating(star)}><Icon name="star" /></button>)}</div><small>Your rating helps improve recommendations.</small></section><section className="panel related-card"><span className="eyebrow">Up next</span><h3>Related resources</h3>{resources.slice(0, 3).map((resource) => <button key={resource.title}><span className={`resource-icon ${resource.tone}`}><Icon name={resource.icon} /></span><span><strong>{resource.title}</strong><small>{resource.meta}</small></span><Icon name="arrow" /></button>)}</section></aside></div></div>
}

export function DocumentPreviewPage({ navigate }) {
  const [page, setPage] = useState(1)
  return <div className="page-stack"><Back navigate={navigate} to="resources">Back to resources</Back><PageTitle eyebrow="Toolkit · PDF" title="Career decision workbook" copy="A practical, 18-page workbook for comparing possibilities and choosing your next experiment." actions={<button className="button primary"><Icon name="download" /> Download PDF</button>} /><div className="document-layout"><aside className="panel document-sidebar"><span className="eyebrow">Contents</span>{['What matters now', 'Energy audit', 'Career shortlist', 'Reality check', 'Next experiment'].map((title, index) => <button className={page === index + 1 ? 'active' : ''} onClick={() => setPage(index + 1)} key={title}><span>0{index + 1}</span>{title}</button>)}<div><Icon name="file" /><p><strong>18 pages</strong><small>Updated Aug 15, 2026</small></p></div></aside><main className="document-sheet"><div className="document-brand"><span><Icon name="compass" /></span><strong>PathSeeker</strong><small>Career decision workbook</small></div><span className="eyebrow">Chapter {page}</span><h1>{['What matters to you now?', 'Track what gives you energy', 'Build a thoughtful shortlist', 'Test assumptions against reality', 'Choose one small experiment'][page - 1]}</h1><p className="document-lead">Use this page to turn a broad career question into something you can observe, compare, and act on.</p><div className="worksheet-box"><span>Reflection prompt</span><h3>What would make your work feel meaningful this year?</h3><div /><div /><div /></div><div className="worksheet-grid"><section><strong>More of this</strong><p>Write the tasks, environments, and people that bring out your best.</p></section><section><strong>Less of this</strong><p>Notice what consistently drains focus or makes progress harder.</p></section></div><footer><span>PathSeeker Career Passport</span><strong>{page} / 18</strong></footer></main></div></div>
}

export function StoryDetailPage({ navigate }) {
  return <div className="page-stack"><Back navigate={navigate} to="stories">Back to success stories</Back><section className="story-detail-hero"><div><span className="eyebrow">Career change · Design</span><h1>“My psychology degree became my UX superpower.”</h1><p>Aisha Rahman · Psychology graduate → Junior UX Designer</p><div className="story-tags"><span>5-month journey</span><span>Karachi, Pakistan</span><span>First design role</span></div></div><div className="story-portrait">AR</div></section><div className="story-detail-layout"><main className="panel story-article"><blockquote>“I thought changing direction meant starting over. It turned out I already had the hardest skill to teach: understanding people.”</blockquote><p>After graduation, Aisha knew she wanted people-centered work but could not see how her psychology degree connected to technology. A PathSeeker quiz surfaced UX research, content design, and product roles.</p><h2>The turning point</h2><p>Instead of enrolling in another degree, she tested the direction with one short research project. She interviewed students about campus services and redesigned a confusing sign-up flow.</p><h2>What changed</h2><p>That first project became a portfolio case study. Four months later, she began interviewing and accepted a junior UX role at Looma.</p></main><aside className="story-timeline panel"><span className="eyebrow">Aisha’s timeline</span>{[['01','Explored','Completed the Career Passport quiz'],['02','Tested','Took a two-week UX foundations course'],['03','Built','Created two research-led portfolio projects'],['04','Moved','Accepted her first junior UX role']].map(([number, title, copy]) => <div key={number}><span>{number}</span><p><strong>{title}</strong><small>{copy}</small></p></div>)}<button className="button primary" onClick={() => navigate('submit-story')}>Share your story</button></aside></div></div>
}

export function SubmitStoryPage({ navigate }) {
  const [step, setStep] = useState(1)
  const [sent, setSent] = useState(false)
  if (sent) return <div className="submission-success"><img src="/assets/navi/navi-celebrating.png" alt="Navi celebrating" /><span><Icon name="check" /></span><h1>Your story is with our review team.</h1><p>We’ll email you after an editor reviews it. You can still update your draft from your profile.</p><button className="button primary" onClick={() => navigate('stories')}>Back to stories</button></div>
  return <div className="page-stack"><Back navigate={navigate} to="stories">Back to success stories</Back><PageTitle eyebrow={`Share your journey · Step ${step} of 3`} title="Your path could help someone else begin" copy="Tell the story in your own words. Nothing is published until you approve the final edit." /><div className="submission-layout"><form className="panel story-form" onSubmit={(event) => { event.preventDefault(); if (step < 3) setStep(step + 1); else setSent(true) }}>{step === 1 && <><h2>Start with the transition</h2><div className="form-grid"><label>Story title<input defaultValue="How psychology led me to UX design" /></label><label>Current role<input defaultValue="Junior UX Designer" /></label><label>Where did you start?<input defaultValue="Psychology graduate" /></label><label>Where are you now?<input defaultValue="Looma design team" /></label></div></>}{step === 2 && <><h2>Tell us what happened</h2><label>Your challenge<textarea defaultValue="I knew I wanted people-centered work, but I could not see how my degree connected to technology." /></label><label>Your turning point<textarea defaultValue="I tested UX research with one small campus project and realized my psychology training was an advantage." /></label><label>Your outcome<textarea defaultValue="Five months later, I accepted my first junior UX role." /></label></>}{step === 3 && <><h2>Review and permissions</h2><div className="story-preview"><span className="avatar">AR</span><div><small>Draft story</small><h3>How psychology led me to UX design</h3><p>Psychology graduate → Junior UX Designer</p></div></div><label className="check-row"><input type="checkbox" defaultChecked /> I confirm this is my story and PathSeeker may contact me to edit it.</label><label className="check-row"><input type="checkbox" defaultChecked /> I approve displaying my first name, role, and career transition.</label></>}<div className="form-actions"><button className="button ghost" type="button" disabled={step === 1} onClick={() => setStep(step - 1)}>Back</button><button className="button primary" type="submit">{step === 3 ? 'Submit for review' : 'Continue'} <Icon name="arrow" /></button></div></form><aside className="submission-guide"><img src={`/assets/navi/navi-${step === 3 ? 'celebrating' : 'explaining'}.png`} alt="Navi guiding your story" /><div className="panel"><span className="eyebrow">A good story includes</span><ul><li><Icon name="check" /> The uncertainty you started with</li><li><Icon name="check" /> One practical turning point</li><li><Icon name="check" /> What you learned along the way</li></ul></div></aside></div></div>
}

export function HelpCenterPage() {
  const [query, setQuery] = useState('')
  const topics = useMemo(() => ['Building your Career Passport', 'Understanding match scores', 'Managing saved careers and notes', 'Quiz privacy and personalization', 'Account security and data', 'Using Navi voice guidance'].filter((topic) => topic.toLowerCase().includes(query.toLowerCase())), [query])
  return <div className="page-stack"><section className="help-hero"><span className="eyebrow">Help center</span><h1>How can we help?</h1><p>Find quick answers about your Career Passport, matches, account, and privacy.</p><div><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search help topics" /></div></section><section className="help-topic-grid">{topics.map((topic, index) => <button className="panel" key={topic}><span className={`career-icon ${['mint','lavender','blue','amber','rose','navy'][index] || 'mint'}`}><Icon name={['compass','sparkles','bookmark','shield','lock','mic'][index] || 'help'} /></span><strong>{topic}</strong><p>Step-by-step guidance and common questions.</p><Icon name="arrow" /></button>)}</section><section className="contact-strip panel"><img src="/assets/navi/navi-listening.png" alt="Navi listening" /><div><span className="eyebrow">Still need a hand?</span><h2>Talk to the PathSeeker team</h2><p>Send a message and we’ll get back to you within one working day.</p></div><button className="button primary">Contact support <Icon name="message" /></button></section></div>
}
