import { useMemo, useState } from 'react'
import Icon from '../components/Icon'
import { careers, quizQuestions, resources, stories } from '../data'

const NaviPrompt = ({ pose = 'explaining', title, children, action, onAction }) => (
  <div className="navi-prompt">
    <div className="navi-prompt-avatar"><img src={`/assets/navi/navi-${pose}.png`} alt="Navi" /></div>
    <div><span className="eyebrow">Navi’s note</span><strong>{title}</strong><p>{children}</p></div>
    {action && <button className="button soft small" onClick={onAction}>{action}<Icon name="arrow" size={16} /></button>}
  </div>
)

const SectionHead = ({ eyebrow, title, link, onLink }) => (
  <div className="section-head"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{link && <button onClick={onLink}>{link}<Icon name="arrow" size={16} /></button>}</div>
)

const CareerCard = ({ career, navigate, saved, toggleSaved, compact = false }) => (
  <article className={`career-card ${compact ? 'compact' : ''}`}>
    <div className="career-card-top"><span className={`career-icon ${career.tone}`}><Icon name={career.icon} /></span><button className={`save-button ${saved ? 'saved' : ''}`} onClick={() => toggleSaved?.(career.id)} aria-label="Save career"><Icon name="bookmark" size={18} /></button></div>
    <span className="match-pill"><Icon name="sparkles" size={13} /> {career.match}% match</span>
    <h3>{career.title}</h3><p>{career.field}</p>
    {!compact && <div className="career-meta"><span><Icon name="briefcase" />{career.salary}</span><span><Icon name="trend" />{career.demand}</span></div>}
    <div className="skill-row">{career.skills.slice(0, compact ? 2 : 3).map((skill) => <span key={skill}>{skill}</span>)}</div>
    <button className="card-link" onClick={() => navigate('career-detail', career.id)}>Explore career <Icon name="arrow" size={17} /></button>
  </article>
)

export function DashboardPage({ navigate, onVoice }) {
  const [saved, setSaved] = useState(['data-analyst'])
  const toggleSaved = (id) => setSaved((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id])
  return (
    <div className="dashboard page-stack">
      <section className="dashboard-hero">
        <div className="hero-copy"><span className="eyebrow">Monday, August 24</span><h1>Good morning, Alex <span>👋</span></h1><p>Your career passport is taking shape. You’re one step away from unlocking your full match profile.</p><div className="hero-actions"><button className="button primary" onClick={() => navigate('quiz')}>Continue career quiz <Icon name="arrow" /></button><button className="button soft" onClick={onVoice}><Icon name="mic" /> Talk it through</button></div></div>
        <div className="passport-progress"><div className="progress-ring"><span>72<small>%</small></span></div><div><span className="eyebrow">Passport strength</span><strong>Almost explorer-ready</strong><p>Complete your interests to improve every recommendation.</p><button onClick={() => navigate('profile')}>View passport <Icon name="arrow" size={15} /></button></div></div>
      </section>

      <NaviPrompt pose="explaining" title="I found a pattern worth exploring" action="See why" onAction={() => navigate('recommendations')}>You light up around creative problem-solving. Your top matches blend people insight with technology.</NaviPrompt>

      <section><SectionHead eyebrow="Personalized for you" title="Your strongest career matches" link="See all matches" onLink={() => navigate('recommendations')} /><div className="career-grid">{careers.slice(0, 3).map((career) => <CareerCard key={career.id} career={career} navigate={navigate} saved={saved.includes(career.id)} toggleSaved={toggleSaved} />)}</div></section>

      <div className="dashboard-columns">
        <section className="journey-card panel"><SectionHead eyebrow="Your journey" title="This week’s momentum" /><div className="momentum-score"><strong>3</strong><span>meaningful steps<br /><small>Top 18% of explorers</small></span><Icon name="trend" /></div><div className="journey-steps"><div className="complete"><span><Icon name="check" /></span><p><strong>Built your basic profile</strong><small>Completed Sunday</small></p></div><div className="current"><span>2</span><p><strong>Finish the interest quiz</strong><small>4 questions left · about 3 min</small></p><button onClick={() => navigate('quiz')}>Continue</button></div><div><span>3</span><p><strong>Review your career roadmap</strong><small>Unlocks after your quiz</small></p><Icon name="lock" size={17} /></div></div></section>
        <section className="continue-card panel"><SectionHead eyebrow="Continue learning" title="Picked for your goals" link="All resources" onLink={() => navigate('resources')} /><div className="resource-feature"><div className="resource-art"><Icon name="play" size={30} /><span>06:42</span></div><div><span className="resource-type">Mini course</span><h3>UX research: start with why</h3><p>Learn how great designers uncover the real problem.</p><div className="mini-progress"><span style={{ width: '62%' }} /></div><small>62% complete</small></div></div><div className="next-resource"><span className="resource-icon amber"><Icon name="headphones" /></span><div><small>Up next · Podcast</small><strong>Breaking into product design</strong></div><button><Icon name="play" /></button></div></section>
      </div>
    </div>
  )
}

export function QuizPage({ navigate, onVoice }) {
  const [index, setIndex] = useState(0)
  const [selected, setSelected] = useState(0)
  const question = quizQuestions[index]
  const progress = index === 0 ? 42 : 76
  const next = () => { if (index < quizQuestions.length - 1) { setIndex(index + 1); setSelected(null) } else navigate('recommendations') }
  return (
    <div className="quiz-page">
      <div className="quiz-top"><button onClick={() => navigate('dashboard')}><Icon name="close" /> Save and exit</button><div><span>Question {index + 5} of 7</span><div className="quiz-progress"><span style={{ width: `${progress}%` }} /></div><small>{progress}% complete</small></div><button onClick={onVoice}><Icon name="mic" /> Answer with voice</button></div>
      <main className="quiz-layout">
        <section className="quiz-card">
          <span className="eyebrow">{question.eyebrow}</span><h1>{question.question}</h1><p>{question.hint}</p>
          <div className="quiz-options">{question.options.map(([label, icon], optionIndex) => <button key={label} className={selected === optionIndex ? 'selected' : ''} onClick={() => setSelected(optionIndex)}><span className="option-letter">{String.fromCharCode(65 + optionIndex)}</span><span className={`option-icon tone-${optionIndex}`}><Icon name={icon} /></span><strong>{label}</strong><span className="radio"><Icon name="check" size={14} /></span></button>)}</div>
          <div className="quiz-actions"><button className="button ghost" onClick={() => index > 0 ? setIndex(index - 1) : navigate('dashboard')}><Icon name="arrowLeft" /> Back</button><button className="button primary" disabled={selected === null} onClick={next}>{index === quizQuestions.length - 1 ? 'See my results' : 'Next question'} <Icon name="arrow" /></button></div>
        </section>
        <aside className="quiz-navi"><div className="navi-aura" /><img src={`/assets/navi/navi-${selected === null ? 'thinking' : 'explaining'}.png`} alt="Navi thinking" /><div className="quiz-tip"><Icon name="sparkles" /><p>{selected === null ? 'Go with your first instinct. We’re looking for patterns, not perfect answers.' : 'That’s useful! It tells me what kind of problems naturally pull you in.'}</p></div><button onClick={onVoice}><span className="voice-pulse mini"><Icon name="mic" /></span><span><strong>Rather say it out loud?</strong><small>Talk with Navi</small></span><Icon name="arrow" /></button></aside>
      </main>
    </div>
  )
}

export function RecommendationsPage({ navigate, onVoice }) {
  const [saved, setSaved] = useState(['ux-designer'])
  const toggleSaved = (id) => setSaved((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id])
  return (
    <div className="recommendations page-stack">
      <section className="results-hero"><div><span className="eyebrow"><Icon name="sparkles" size={15} /> Your quiz results are ready</span><h1>You’re a <em>Thoughtful Builder</em></h1><p>You combine empathy, curiosity, and structured thinking. You do your best work when you can understand a real problem, make sense of it, and shape something useful.</p><div className="trait-row"><span><Icon name="heart" /> Empathetic</span><span><Icon name="sparkles" /> Curious</span><span><Icon name="chart" /> Analytical</span><span><Icon name="pen" /> Creative</span></div><button className="button soft" onClick={onVoice}><Icon name="mic" /> Hear Navi explain my results</button></div><div className="results-navi"><img src="/assets/navi/navi-celebrating.png" alt="Navi celebrating your results" /><div className="results-badge"><Icon name="check" /><span><strong>Profile unlocked</strong><small>Based on 7 answers</small></span></div></div></section>
      <section><SectionHead eyebrow="Ranked for you" title="Your top career matches" /><div className="result-list">{careers.slice(0, 4).map((career, index) => <article key={career.id} className="result-card"><span className="rank">0{index + 1}</span><span className={`career-icon ${career.tone}`}><Icon name={career.icon} /></span><div className="result-main"><div><span className="match-pill">{career.match}% match</span><h3>{career.title}</h3><p>{career.summary}</p></div><div className="career-meta"><span><small>Typical salary</small><strong>{career.salary}</strong></span><span><small>Job outlook</small><strong>{career.growth} growth</strong></span><span><small>Best-fit strength</small><strong>{career.skills[0]}</strong></span></div><div className="skill-row">{career.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div><div className="result-actions"><button className={`save-button ${saved.includes(career.id) ? 'saved' : ''}`} onClick={() => toggleSaved(career.id)}><Icon name="bookmark" /></button><button className="button primary small" onClick={() => navigate('career-detail', career.id)}>View career <Icon name="arrow" size={16} /></button></div></article>)}</div></section>
      <NaviPrompt pose="pointing-left" title="Not seeing what you expected?" action="Refine my matches" onAction={() => navigate('quiz')}>Your results are a starting point, not a label. We can adjust your priorities or explore a different side of your strengths.</NaviPrompt>
    </div>
  )
}

export function CareerBankPage({ navigate }) {
  const [query, setQuery] = useState('')
  const [field, setField] = useState('All careers')
  const [saved, setSaved] = useState([])
  const filtered = useMemo(() => careers.filter((career) => (field === 'All careers' || career.field.includes(field)) && `${career.title} ${career.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query, field])
  const toggleSaved = (id) => setSaved((items) => items.includes(id) ? items.filter((x) => x !== id) : [...items, id])
  return (
    <div className="career-bank page-stack">
      <section className="page-intro"><div><span className="eyebrow">Career Bank</span><h1>Explore where you could go</h1><p>Compare salary, skills, demand, and the work itself across hundreds of career paths.</p></div><div className="intro-stat"><strong>240+</strong><span>career profiles<br /><small>curated by experts</small></span></div></section>
      <section className="search-panel panel"><div className="career-search"><Icon name="search" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search careers, skills, or industries" /><button>Search</button></div><div className="filter-row"><div className="filter-chips">{['All careers', 'Design', 'Technology', 'Business', 'Data'].map((item) => <button key={item} className={field === item ? 'active' : ''} onClick={() => setField(item)}>{item}</button>)}</div><button className="advanced-filter"><Icon name="filter" /> More filters <span>2</span></button></div><div className="active-filters"><span>High demand <button>×</button></span><span>$60k+ salary <button>×</button></span><button>Clear all</button></div></section>
      <section><div className="results-bar"><p><strong>{filtered.length || 0} careers</strong> matching your filters</p><label>Sort by <select defaultValue="Best match"><option>Best match</option><option>Highest salary</option><option>Fastest growth</option></select></label></div>{filtered.length > 0 ? <div className="career-grid bank-grid">{filtered.map((career) => <CareerCard key={career.id} career={career} navigate={navigate} saved={saved.includes(career.id)} toggleSaved={toggleSaved} />)}</div> : <div className="empty-state"><img src="/assets/navi/navi-thinking.png" alt="Navi thinking" /><h2>No exact matches yet</h2><p>Try a broader keyword or remove one of your filters.</p><button className="button soft" onClick={() => { setQuery(''); setField('All careers') }}>Clear search</button></div>}</section>
    </div>
  )
}

export function CareerDetailPage({ navigate, careerId = 'ux-designer' }) {
  const career = careers.find((item) => item.id === careerId) || careers[0]
  const [saved, setSaved] = useState(false)
  return (
    <div className="career-detail page-stack">
      <button className="back-link" onClick={() => navigate('careers')}><Icon name="arrowLeft" /> Back to Career Bank</button>
      <section className="career-detail-hero"><div className="career-title-block"><span className={`career-icon xl ${career.tone}`}><Icon name={career.icon} size={30} /></span><div><span className="match-pill"><Icon name="sparkles" size={13} /> {career.match}% match for you</span><h1>{career.title}</h1><p>{career.field} · Updated August 2026</p></div></div><div className="detail-actions"><button className={`button soft ${saved ? 'saved' : ''}`} onClick={() => setSaved(!saved)}><Icon name="bookmark" /> {saved ? 'Saved' : 'Save career'}</button><button className="button primary" onClick={() => navigate('quiz')}>Add to my roadmap <Icon name="plus" /></button></div></section>
      <div className="detail-layout"><div className="detail-main"><section className="panel prose-card"><span className="eyebrow">Career snapshot</span><h2>Design experiences that make technology feel simple.</h2><p>{career.summary} UX designers work closely with users, product managers, and engineers to research needs, test ideas, and refine every interaction.</p><div className="snapshot-grid"><div><span className="snapshot-icon"><Icon name="briefcase" /></span><small>Typical salary</small><strong>{career.salary}</strong><p>US national range</p></div><div><span className="snapshot-icon"><Icon name="trend" /></span><small>Projected growth</small><strong>{career.growth}</strong><p>Over the next 10 years</p></div><div><span className="snapshot-icon"><Icon name="clock" /></span><small>Time to job-ready</small><strong>6–12 months</strong><p>With focused learning</p></div></div></section>
        <section className="panel"><SectionHead eyebrow="A day in the work" title={`What ${career.title}s actually do`} /><div className="responsibility-list"><div><span>01</span><p><strong>Understand the real problem</strong><small>Interview people, observe behavior, and turn messy needs into clear opportunities.</small></p></div><div><span>02</span><p><strong>Explore and prototype ideas</strong><small>Sketch flows and build testable prototypes before expensive development begins.</small></p></div><div><span>03</span><p><strong>Collaborate and improve</strong><small>Partner across a team, use feedback, and refine details until the experience feels right.</small></p></div></div></section>
        <section className="panel"><SectionHead eyebrow="Skills map" title="What you’ll need to thrive" /><div className="skills-map"><div><strong>Core skills</strong>{career.skills.map((skill, i) => <div key={skill}><span>{skill}</span><div><i style={{ width: `${88 - i * 9}%` }} /></div><small>{88 - i * 9}%</small></div>)}</div><div><strong>Tools to learn</strong><div className="tool-grid"><span>Fi<strong>Figma</strong></span><span>Mi<strong>Miro</strong></span><span>Nt<strong>Notion</strong></span><span>Ma<strong>Maze</strong></span></div></div></div></section>
        <section className="panel roadmap"><SectionHead eyebrow="Your personalized route" title="A practical path into this career" /><div className="roadmap-line"><div className="done"><span><Icon name="check" /></span><p><small>Step 1 · Complete</small><strong>Understand the foundations</strong><em>2 weeks</em></p></div><div className="current"><span>2</span><p><small>Step 2 · Your next move</small><strong>Practice research and prototyping</strong><em>6–8 weeks</em></p><button>View learning plan</button></div><div><span>3</span><p><small>Step 3</small><strong>Build two portfolio projects</strong><em>8–12 weeks</em></p></div><div><span>4</span><p><small>Step 4</small><strong>Prepare and start applying</strong><em>4 weeks</em></p></div></div></section></div>
        <aside className="detail-aside"><NaviPrompt pose="explaining" title="Why this fits you">Your empathy helps you notice what people need, while your analytical side enjoys turning that insight into a clear system.</NaviPrompt><div className="panel fit-card"><span className="eyebrow">Your fit</span><div className="fit-score"><strong>{career.match}%</strong><div><span style={{ width: `${career.match}%` }} /></div></div><ul><li><Icon name="check" /> Strong interest alignment</li><li><Icon name="check" /> Natural skill overlap</li><li><Icon name="check" /> Matches your work style</li></ul><button onClick={() => navigate('recommendations')}>Compare with other matches</button></div><div className="panel expert-card"><div className="expert-video"><span><Icon name="play" /></span><small>08:14</small></div><span className="eyebrow">Expert story</span><h3>“What I wish I knew before UX”</h3><p>Maya Chen · Senior Product Designer</p><button>Watch story <Icon name="arrow" /></button></div></aside></div>
    </div>
  )
}

export function ResourcesPage() {
  const [tab, setTab] = useState('All')
  const tabs = ['All', 'Courses', 'Videos', 'Podcasts', 'Documents']
  const filtered = tab === 'All' ? resources : resources.filter((item) => `${item.type}s` === tab || (tab === 'Documents' && ['Guide', 'Toolkit'].includes(item.type)))
  return (
    <div className="resources-page page-stack"><section className="page-intro resources-intro"><div><span className="eyebrow">Resource library</span><h1>Learn what moves you forward</h1><p>Practical, expert-led resources matched to your goals and saved careers.</p></div><div className="resource-search"><Icon name="search" /><input placeholder="Search the library" /></div></section><div className="tab-row">{tabs.map((item) => <button className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div><section className="featured-resource"><div className="feature-art"><span className="resource-type">Featured mini course</span><div className="feature-play"><Icon name="play" /></div><small>6 lessons · 42 min</small></div><div><span className="eyebrow">Recommended from your matches</span><h2>Think like a UX designer</h2><p>Learn the mindset behind human-centered design through a practical mini project. No previous design experience needed.</p><div className="teacher"><span>MC</span><p><strong>Maya Chen</strong><small>Senior Product Designer · Looma</small></p></div><button className="button primary">Continue course <Icon name="arrow" /></button></div></section><section><SectionHead eyebrow="Curated for your path" title={`${tab === 'All' ? 'Explore all resources' : tab}`} /><div className="resource-grid">{filtered.map((resource) => <article key={resource.title} className="resource-card"><div className={`resource-cover ${resource.tone}`}><Icon name={resource.icon} size={32} /><span>{resource.type}</span><button><Icon name="bookmark" /></button></div><div><span className="resource-type">{resource.type}</span><h3>{resource.title}</h3><p>{resource.meta}</p>{resource.progress > 0 ? <><div className="mini-progress"><span style={{ width: `${resource.progress}%` }} /></div><small>{resource.progress}% complete</small></> : <button className="card-link">Open resource <Icon name="arrow" /></button>}</div></article>)}</div></section></div>
  )
}

export function SavedPage({ navigate }) {
  const [tab, setTab] = useState('Careers')
  return (
    <div className="saved-page page-stack"><section className="page-intro"><div><span className="eyebrow">Your collection</span><h1>Saved ideas & notes</h1><p>Everything you want to revisit, organized in one calm place.</p></div><button className="button primary"><Icon name="plus" /> New note</button></section><div className="tab-row"><button className={tab === 'Careers' ? 'active' : ''} onClick={() => setTab('Careers')}>Saved careers <span>3</span></button><button className={tab === 'Resources' ? 'active' : ''} onClick={() => setTab('Resources')}>Resources <span>4</span></button><button className={tab === 'Notes' ? 'active' : ''} onClick={() => setTab('Notes')}>My notes <span>5</span></button></div>{tab === 'Careers' && <div className="saved-layout"><section><div className="career-grid two-col">{careers.slice(0, 3).map((career) => <CareerCard key={career.id} career={career} navigate={navigate} saved toggleSaved={() => {}} compact />)}</div></section><aside className="panel notes-preview"><SectionHead eyebrow="Related notes" title="Thoughts to revisit" link="See all" /><article><span className="note-dot mint" /><div><strong>Portfolio ideas</strong><p>Redesign the campus event sign-up flow and test it with five students…</p><small>UX Designer · 2 days ago</small></div></article><article><span className="note-dot blue" /><div><strong>Questions for Sam</strong><p>Ask what a junior analyst really does during their first 90 days.</p><small>Data Analyst · Aug 18</small></div></article><button className="new-note"><Icon name="plus" /> Add a note</button></aside></div>}{tab === 'Resources' && <div className="resource-grid">{resources.slice(0, 4).map((resource) => <article key={resource.title} className="resource-card"><div className={`resource-cover ${resource.tone}`}><Icon name={resource.icon} size={32} /><span>{resource.type}</span></div><div><span className="resource-type">{resource.type}</span><h3>{resource.title}</h3><p>{resource.meta}</p></div></article>)}</div>}{tab === 'Notes' && <div className="notes-grid">{['Portfolio ideas', 'Questions for Sam', 'What energizes me', 'Data skills to practice', 'Questions for Navi'].map((title, i) => <article key={title} className="panel"><div><span className={`note-dot ${['mint','blue','lavender','amber','rose'][i]}`} /><button><Icon name="more" /></button></div><h3>{title}</h3><p>{['Redesign the campus event sign-up flow and test it with five students.', 'Ask what a junior analyst really does during their first 90 days.', 'Facilitating workshops, visual problem solving, and making complex ideas clear.', 'SQL joins, dashboard design, and presenting a recommendation with confidence.', 'How do I choose between two careers that fit different sides of me?'][i]}</p><small>Edited {i + 1} days ago</small></article>)}</div>}</div>
  )
}

export function StoriesPage() {
  return (
    <div className="stories-page page-stack"><section className="stories-hero"><div><span className="eyebrow">Real people · Real pivots</span><h1>There’s more than one way forward.</h1><p>Meet people who followed their curiosity, built new skills, and found work that fits.</p><button className="button primary">Share your story <Icon name="arrow" /></button></div><div className="story-collage"><span className="portrait p1">AR</span><span className="portrait p2">DK</span><span className="portrait p3">FN</span><div><strong>2,400+</strong><small>career journeys shared</small></div></div></section><section className="featured-story panel"><div className="story-video"><span><Icon name="play" size={28} /></span><small>04:36</small></div><div><span className="eyebrow">Featured journey</span><h2>“My psychology degree became my UX superpower.”</h2><blockquote>“Once I stopped trying to hide my background, everything clicked. Understanding people was exactly the point.”</blockquote><div className="story-person"><span>AR</span><p><strong>Aisha Rahman</strong><small>Psychology graduate → UX Designer</small></p></div><div className="story-tags"><span>Career change</span><span>Design</span><span>5-month journey</span></div></div></section><section><SectionHead eyebrow="Community voices" title="More paths worth knowing" /><div className="story-grid">{stories.map((story) => <article key={story.name}><Icon name="message" /><p>“{story.quote}”</p><div><span className={`portrait ${story.tone}`}>{story.initials}</span><span><strong>{story.name}</strong><small>{story.role}</small></span></div></article>)}</div></section><NaviPrompt pose="walking-profile" title="Your path can move, too">Careers are built one experiment at a time. Save the stories that make your next step feel possible.</NaviPrompt></div>
  )
}

export function ProfilePage() {
  const [section, setSection] = useState('Passport')
  return (
    <div className="profile-page page-stack"><section className="profile-hero"><div className="profile-avatar">AM<button><Icon name="edit" size={15} /></button></div><div><span className="eyebrow">Career Passport</span><h1>Alex Morgan</h1><p>Student · Karachi, Pakistan · Exploring design & technology</p><div><span><Icon name="sparkles" /> Thoughtful Builder</span><span><Icon name="target" /> 3 saved careers</span></div></div><button className="button soft"><Icon name="download" /> Download passport</button></section><div className="settings-layout"><aside className="settings-nav">{['Passport', 'Personal details', 'Preferences', 'Notifications', 'Privacy & data'].map((item) => <button className={section === item ? 'active' : ''} key={item} onClick={() => setSection(item)}><Icon name={item === 'Passport' ? 'compass' : item === 'Personal details' ? 'users' : item === 'Preferences' ? 'settings' : item === 'Notifications' ? 'bell' : 'shield'} />{item}<Icon name="chevron" /></button>)}</aside><section className="settings-content panel">{section === 'Passport' ? <><SectionHead eyebrow="Your profile" title="Career passport strength" /><div className="passport-score"><div className="progress-ring"><span>72<small>%</small></span></div><div><strong>Almost explorer-ready</strong><p>Add your work preferences and one experience to improve your matches.</p><button className="button primary small">Complete passport <Icon name="arrow" /></button></div></div><div className="passport-sections"><article><span><Icon name="heart" /></span><div><small>Interests</small><strong>Design, technology, helping people</strong></div><button><Icon name="edit" /></button></article><article><span><Icon name="sparkles" /></span><div><small>Top strengths</small><strong>Empathy, communication, problem-solving</strong></div><button><Icon name="edit" /></button></article><article><span><Icon name="target" /></span><div><small>Current goal</small><strong>Discover careers that fit me</strong></div><button><Icon name="edit" /></button></article><article className="incomplete"><span><Icon name="plus" /></span><div><small>Experience</small><strong>Add education or work experience</strong></div><button>Add</button></article></div></> : <SettingsForm section={section} />}</section></div></div>
  )
}

function SettingsForm({ section }) {
  if (section === 'Notifications') return <><SectionHead eyebrow="Stay informed" title="Notification preferences" />{['Weekly career insights', 'New resources for saved careers', 'Learning reminders', 'Product updates'].map((item, i) => <label className="toggle-row" key={item}><span><strong>{item}</strong><small>{i === 0 ? 'A short personalized digest every Monday' : 'Helpful updates, never noise'}</small></span><input type="checkbox" defaultChecked={i < 3} /><i /></label>)}</>
  if (section === 'Privacy & data') return <><SectionHead eyebrow="Your control" title="Privacy & data" /><div className="privacy-list"><button><span><Icon name="download" /></span><p><strong>Download my data</strong><small>Get a copy of your profile, quiz answers, notes, and saved content.</small></p><Icon name="chevron" /></button><button><span><Icon name="shield" /></span><p><strong>AI personalization</strong><small>Choose whether activity can improve your recommendations.</small></p><Icon name="chevron" /></button><button className="danger"><span><Icon name="close" /></span><p><strong>Delete account</strong><small>Permanently remove your PathSeeker account and data.</small></p><Icon name="chevron" /></button></div></>
  return <><SectionHead eyebrow="Account settings" title={section} /><div className="form-grid"><label>Full name<input defaultValue="Alex Morgan" /></label><label>Email address<input defaultValue="alex@example.com" /></label><label>Current stage<select defaultValue="Student"><option>Student</option><option>Graduate</option><option>Working professional</option></select></label><label>Location<input defaultValue="Karachi, Pakistan" /></label><label className="full">Short bio<textarea defaultValue="Curious student exploring careers where design, technology, and helping people come together." /></label></div><button className="button primary">Save changes</button></>
}

export function FeedbackPage({ navigate }) {
  const [sent, setSent] = useState(false)
  if (sent) return <div className="feedback-success"><img src="/assets/navi/navi-celebrating.png" alt="Navi celebrating" /><span className="success-check"><Icon name="check" /></span><h1>Thanks for helping us grow.</h1><p>Your feedback has been sent to the PathSeeker team.</p><button className="button primary" onClick={() => navigate('dashboard')}>Back to dashboard</button></div>
  return <div className="feedback-page"><section className="feedback-copy"><span className="eyebrow">Send feedback</span><h1>Help make the journey better</h1><p>Found something confusing? Have an idea? We read every message.</p><img src="/assets/navi/navi-listening.png" alt="Navi listening" /></section><form className="feedback-card panel" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><label>What is this about?<div className="feedback-types">{['Idea', 'Problem', 'Content', 'Other'].map((item, i) => <button type="button" className={i === 0 ? 'active' : ''} key={item}>{item}</button>)}</div></label><label>How was your experience?<div className="rating-row">{[1,2,3,4,5].map((item) => <button type="button" key={item} className={item <= 4 ? 'active' : ''}><Icon name="star" /></button>)}</div></label><label>Tell us more<textarea required placeholder="What would you like us to know?" defaultValue="I’d love a way to compare two career roadmaps side by side." /></label><label className="check-row"><input type="checkbox" defaultChecked /> You may contact me about this feedback</label><button className="button primary full" type="submit">Send feedback <Icon name="arrow" /></button></form></div>
}
