import Icon from '../../components/Icon'
import PageTitle from '../../components/common/PageTitle'
import Back from '../../components/common/BackButton'
import { useState } from 'react'

export default function DocumentPreviewPage({ navigate }) {
  const [page, setPage] = useState(1)
  return <div className="page-stack"><Back navigate={navigate} to="resources">Back to resources</Back><PageTitle eyebrow="Toolkit · PDF" title="Career decision workbook" copy="A practical, 18-page workbook for comparing possibilities and choosing your next experiment." actions={<button className="button primary"><Icon name="download" /> Download PDF</button>} /><div className="document-layout"><aside className="panel document-sidebar"><span className="eyebrow">Contents</span>{['What matters now', 'Energy audit', 'Career shortlist', 'Reality check', 'Next experiment'].map((title, index) => <button className={page === index + 1 ? 'active' : ''} onClick={() => setPage(index + 1)} key={title}><span>0{index + 1}</span>{title}</button>)}<div><Icon name="file" /><p><strong>18 pages</strong><small>Updated Aug 15, 2026</small></p></div></aside><main className="document-sheet"><div className="document-brand"><span><Icon name="compass" /></span><strong>PathSeeker</strong><small>Career decision workbook</small></div><span className="eyebrow">Chapter {page}</span><h1>{['What matters to you now?', 'Track what gives you energy', 'Build a thoughtful shortlist', 'Test assumptions against reality', 'Choose one small experiment'][page - 1]}</h1><p className="document-lead">Use this page to turn a broad career question into something you can observe, compare, and act on.</p><div className="worksheet-box"><span>Reflection prompt</span><h3>What would make your work feel meaningful this year?</h3><div /><div /><div /></div><div className="worksheet-grid"><section><strong>More of this</strong><p>Write the tasks, environments, and people that bring out your best.</p></section><section><strong>Less of this</strong><p>Notice what consistently drains focus or makes progress harder.</p></section></div><footer><span>PathSeeker Career Passport</span><strong>{page} / 18</strong></footer></main></div></div>
}
