import Icon from '../../components/Icon'
import SectionHead from '../../components/user/SectionHead'
import SettingsForm from '../../components/user/SettingsForm'
import { useState } from 'react'

export default function ProfilePage() {
  const [section, setSection] = useState('Passport')
  return (
    <div className="profile-page page-stack"><section className="profile-hero"><div className="profile-avatar">AM<button><Icon name="edit" size={15} /></button></div><div><span className="eyebrow">Career Passport</span><h1>Alex Morgan</h1><p>Student · Karachi, Pakistan · Exploring design & technology</p><div><span><Icon name="sparkles" /> Thoughtful Builder</span><span><Icon name="target" /> 3 saved careers</span></div></div><button className="button soft"><Icon name="download" /> Download passport</button></section><div className="settings-layout"><aside className="settings-nav">{['Passport', 'Personal details', 'Preferences', 'Notifications', 'Privacy & data'].map((item) => <button className={section === item ? 'active' : ''} key={item} onClick={() => setSection(item)}><Icon name={item === 'Passport' ? 'compass' : item === 'Personal details' ? 'users' : item === 'Preferences' ? 'settings' : item === 'Notifications' ? 'bell' : 'shield'} />{item}<Icon name="chevron" /></button>)}</aside><section className="settings-content panel">{section === 'Passport' ? <><SectionHead eyebrow="Your profile" title="Career passport strength" /><div className="passport-score"><div className="progress-ring"><span>72<small>%</small></span></div><div><strong>Almost explorer-ready</strong><p>Add your work preferences and one experience to improve your matches.</p><button className="button primary small">Complete passport <Icon name="arrow" /></button></div></div><div className="passport-sections"><article><span><Icon name="heart" /></span><div><small>Interests</small><strong>Design, technology, helping people</strong></div><button><Icon name="edit" /></button></article><article><span><Icon name="sparkles" /></span><div><small>Top strengths</small><strong>Empathy, communication, problem-solving</strong></div><button><Icon name="edit" /></button></article><article><span><Icon name="target" /></span><div><small>Current goal</small><strong>Discover careers that fit me</strong></div><button><Icon name="edit" /></button></article><article className="incomplete"><span><Icon name="plus" /></span><div><small>Experience</small><strong>Add education or work experience</strong></div><button>Add</button></article></div></> : <SettingsForm section={section} />}</section></div></div>
  )
}
