import Icon from '../../components/Icon'
import PageTitle from '../../components/common/PageTitle'
import Back from '../../components/common/BackButton'
import { useState } from 'react'

export default function SubmitStoryPage({ navigate }) {
  const [step, setStep] = useState(1)
  const [sent, setSent] = useState(false)
  if (sent) return <div className="submission-success"><img src="/assets/navi/navi-celebrating.png" alt="Navi celebrating" /><span><Icon name="check" /></span><h1>Your story is with our review team.</h1><p>We’ll email you after an editor reviews it. You can still update your draft from your profile.</p><button className="button primary" onClick={() => navigate('stories')}>Back to stories</button></div>
  return <div className="page-stack"><Back navigate={navigate} to="stories">Back to success stories</Back><PageTitle eyebrow={`Share your journey · Step ${step} of 3`} title="Your path could help someone else begin" copy="Tell the story in your own words. Nothing is published until you approve the final edit." /><div className="submission-layout"><form className="panel story-form" onSubmit={(event) => { event.preventDefault(); if (step < 3) setStep(step + 1); else setSent(true) }}>{step === 1 && <><h2>Start with the transition</h2><div className="form-grid"><label>Story title<input defaultValue="How psychology led me to UX design" /></label><label>Current role<input defaultValue="Junior UX Designer" /></label><label>Where did you start?<input defaultValue="Psychology graduate" /></label><label>Where are you now?<input defaultValue="Looma design team" /></label></div></>}{step === 2 && <><h2>Tell us what happened</h2><label>Your challenge<textarea defaultValue="I knew I wanted people-centered work, but I could not see how my degree connected to technology." /></label><label>Your turning point<textarea defaultValue="I tested UX research with one small campus project and realized my psychology training was an advantage." /></label><label>Your outcome<textarea defaultValue="Five months later, I accepted my first junior UX role." /></label></>}{step === 3 && <><h2>Review and permissions</h2><div className="story-preview"><span className="avatar">AR</span><div><small>Draft story</small><h3>How psychology led me to UX design</h3><p>Psychology graduate → Junior UX Designer</p></div></div><label className="check-row"><input type="checkbox" defaultChecked /> I confirm this is my story and PathSeeker may contact me to edit it.</label><label className="check-row"><input type="checkbox" defaultChecked /> I approve displaying my first name, role, and career transition.</label></>}<div className="form-actions"><button className="button ghost" type="button" disabled={step === 1} onClick={() => setStep(step - 1)}>Back</button><button className="button primary" type="submit">{step === 3 ? 'Submit for review' : 'Continue'} <Icon name="arrow" /></button></div></form><aside className="submission-guide"><img src={`/assets/navi/navi-${step === 3 ? 'celebrating' : 'explaining'}.png`} alt="Navi guiding your story" /><div className="panel"><span className="eyebrow">A good story includes</span><ul><li><Icon name="check" /> The uncertainty you started with</li><li><Icon name="check" /> One practical turning point</li><li><Icon name="check" /> What you learned along the way</li></ul></div></aside></div></div>
}
