import Icon from '../../components/Icon'
import Head from '../../components/admin/AdminEditorHead'
import { useEffect, useState } from 'react'
import { apiRequest, endpoints } from '../../services/pathseekerApi'
const blank = { title: '', slug: '', summary: '', body: '', category: 'General', sortOrder: 0, published: false }
export default function AdminHelpPage() {
  const [articles, setArticles] = useState([]); const [editor, setEditor] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const { data } = await apiRequest(`${endpoints.admin.help}?limit=100`); setArticles(data.articles || []) } catch (err) { setError(err.message || 'Could not load help content.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const save = async () => { try { const endpoint = editor._id ? endpoints.admin.helpItem(editor._id) : endpoints.admin.helpCreate; await apiRequest(endpoint, { method: editor._id ? 'PATCH' : 'POST', body: JSON.stringify(editor) }); setEditor(null); await load() } catch (err) { setError(err.message || 'Could not save help article.') } }
  const remove = async id => { if (!window.confirm('Delete this help article?')) return; try { await apiRequest(endpoints.admin.helpItem(id), { method: 'DELETE' }); await load() } catch (err) { setError(err.message || 'Could not delete help article.') } }
  return <div className="admin-stack"><Head eyebrow="PathSeeker support" title="Help center CMS" copy="Manage persistent user-facing help articles. Changes are published through the real API."><button className="button soft" onClick={load}><Icon name="refresh"/> Refresh</button><button className="button primary" onClick={() => setEditor(blank)}><Icon name="plus"/> New article</button></Head>{error && <div className="panel form-error" role="alert">{error}</div>}{loading ? <div className="panel">Loading help articles…</div> : <section className="panel admin-table"><table><thead><tr><th>Title</th><th>Category</th><th>Status</th><th/></tr></thead><tbody>{articles.map(article => <tr key={article._id}><td>{article.title}</td><td>{article.category}</td><td>{article.published ? 'Published' : 'Draft'}</td><td><button className="button ghost small" onClick={() => setEditor(article)}>Edit</button><button className="button ghost small" onClick={() => remove(article._id)}>Delete</button></td></tr>)}</tbody></table></section>}{editor && <section className="panel admin-editor-form"><h2>{editor._id ? 'Edit article' : 'New article'}</h2><div className="form-grid"><label>Title<input value={editor.title} onChange={e => setEditor({...editor,title:e.target.value})}/></label><label>Slug<input value={editor.slug} onChange={e => setEditor({...editor,slug:e.target.value})}/></label><label>Category<input value={editor.category} onChange={e => setEditor({...editor,category:e.target.value})}/></label><label>Order<input type="number" min="0" value={editor.sortOrder} onChange={e => setEditor({...editor,sortOrder:e.target.value})}/></label><label className="full">Summary<textarea value={editor.summary} onChange={e => setEditor({...editor,summary:e.target.value})}/></label><label className="full">Body<textarea rows="12" value={editor.body} onChange={e => setEditor({...editor,body:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={editor.published} onChange={e => setEditor({...editor,published:e.target.checked})}/> Published</label></div><div className="form-actions"><button className="button ghost" onClick={() => setEditor(null)}>Cancel</button><button className="button primary" onClick={save} disabled={!editor.title || !editor.slug || !editor.body}>Save article</button></div></section>}</div>
}
