import Icon from '../../components/Icon'
import Head from '../../components/admin/AdminEditorHead'
import Field from '../../components/admin/AdminField'
import { useState } from 'react'

export default function AdminCareerEditor({ navigate }) {
  const [tab, setTab] = useState('Overview')
  return <div className="admin-stack"><Head eyebrow="Career Bank · Editor" title="UX Designer" copy="Maintain the public profile, matching signals, and learning roadmap."><button className="button ghost" onClick={() => navigate('admin-careers')}>Cancel</button><button className="button soft">Save draft</button><button className="button primary">Publish changes</button></Head><div className="editor-tabs">{['Overview','Salary & demand','Skills','Roadmap','Matching'].map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><section className="panel admin-editor-form">{tab === 'Overview' && <div className="editor-section"><h2>Career overview</h2><div className="form-grid"><Field label="Career title"><input defaultValue="UX Designer" /></Field><Field label="Domain"><select defaultValue="Design & Technology"><option>Design & Technology</option><option>Data & Business</option></select></Field><Field label="Short summary"><textarea defaultValue="Shape intuitive digital products by understanding people and turning their needs into thoughtful experiences." /></Field><Field label="Publishing status"><select defaultValue="Published"><option>Published</option><option>Draft</option></select></Field></div></div>}{tab === 'Salary & demand' && <div className="editor-section"><h2>Market outlook</h2><div className="form-grid"><Field label="Minimum salary"><input type="number" defaultValue="72000" /></Field><Field label="Maximum salary"><input type="number" defaultValue="118000" /></Field><Field label="Projected growth"><input defaultValue="13%" /></Field><Field label="Demand label"><select defaultValue="High demand"><option>High demand</option><option>Very high</option><option>Growing</option></select></Field></div></div>}{tab === 'Skills' && <div className="editor-section"><h2>Core skills</h2><div className="tag-editor">{['User research','Figma','Prototyping','Empathy'].map((skill) => <span key={skill}>{skill}<button>×</button></span>)}<button><Icon name="plus" /> Add skill</button></div></div>}{tab === 'Roadmap' && <div className="editor-section"><h2>Learning roadmap</h2>{['Understand the foundations','Practice research and prototyping','Build two portfolio projects','Prepare and start applying'].map((step, index) => <div className="admin-roadmap-row" key={step}><span>{index + 1}</span><input defaultValue={step} /><input defaultValue={['2 weeks','6–8 weeks','8–12 weeks','4 weeks'][index]} /><button><Icon name="more" /></button></div>)}</div>}{tab === 'Matching' && <div className="editor-section"><h2>Matching signals</h2><p>Weights will be stored as numeric fields in the career document.</p>{['Creative problem-solving','Empathy','Structured thinking','Collaboration'].map((signal, index) => <label className="range-row" key={signal}><span>{signal}</span><input type="range" defaultValue={90 - index * 8} /><strong>{90 - index * 8}%</strong></label>)}</div>}</section></div>
}
