import Icon from '../../components/Icon'
import Head from '../../components/admin/AdminEditorHead'
import Field from '../../components/admin/AdminField'
import { useState } from 'react'

export default function AdminStoryReview({ navigate }) {
  const [status, setStatus] = useState('Pending review')
  return <div className="admin-stack"><Head eyebrow="Success stories · Review" title="Aisha Rahman’s journey" copy="Review the submitted story, leave editorial notes, and prepare it for publishing."><button className="button ghost" onClick={() => navigate('admin-stories')}>Back</button><button className="button soft" onClick={() => setStatus('Needs edits')}>Request edits</button><button className="button primary" onClick={() => setStatus('Published')}>Approve & publish</button></Head><div className="review-status"><Icon name={status === 'Published' ? 'check' : 'clock'} /> Current status: <strong>{status}</strong></div><div className="admin-review-layout"><section className="panel review-copy"><span className="eyebrow">Submitted story</span><h2>How psychology led me to UX design</h2><blockquote>“I thought changing direction meant starting over. It turned out I already had the hardest skill to teach: understanding people.”</blockquote><h3>The challenge</h3><p>I knew I wanted people-centered work, but I could not see how my psychology degree connected to technology.</p><h3>The turning point</h3><p>I tested UX research with one small campus project and realized my psychology training was an advantage.</p><h3>The outcome</h3><p>Five months later, I accepted my first junior UX role.</p></section><aside className="panel review-panel"><span className="avatar">AR</span><h3>Aisha Rahman</h3><p>aisha@example.com</p><Field label="Internal editorial note"><textarea defaultValue="Strong story. Ask for one portfolio image and confirm company name before featuring." /></Field><label className="check-row"><input type="checkbox" defaultChecked /> Consent confirmed</label><label className="check-row"><input type="checkbox" /> Feature on homepage</label><button className="button soft full">Save internal note</button></aside></div></div>
}
