import Icon from '../../components/Icon'
import Head from '../../components/admin/AdminEditorHead'
import Field from '../../components/admin/AdminField'
import { useState } from 'react'

export default function AdminUserEditor({ navigate }) {
  const [saved, setSaved] = useState(false)
  return <div className="admin-stack"><Head eyebrow="Community · User record" title="Alex Morgan" copy="Review profile details, engagement, and account access."><button className="button ghost" onClick={() => navigate('admin-users')}>Cancel</button><button className="button primary" onClick={() => setSaved(true)}>Save changes</button></Head>{saved && <div className="admin-toast"><Icon name="check" /> User changes saved to the frontend fixture.</div>}<div className="admin-editor-layout"><section className="panel admin-editor-form"><div className="editor-section"><h2>Personal details</h2><div className="form-grid"><Field label="Full name"><input defaultValue="Alex Morgan" /></Field><Field label="Email"><input defaultValue="alex@example.com" /></Field><Field label="Stage"><select defaultValue="Student"><option>Student</option><option>Graduate</option><option>Professional</option></select></Field><Field label="Location"><input defaultValue="Karachi, Pakistan" /></Field></div></div><div className="editor-section"><h2>Account access</h2><div className="form-grid"><Field label="Status"><select defaultValue="Active"><option>Active</option><option>Inactive</option><option>Suspended</option></select></Field><Field label="Role"><select defaultValue="User"><option>User</option><option>Administrator</option></select></Field></div><label className="toggle-row"><span><strong>Email verified</strong><small>User completed email verification.</small></span><input type="checkbox" defaultChecked /><i /></label></div><div className="danger-zone"><h3>Danger zone</h3><p>Suspend access or remove the user after a confirmation step.</p><button className="button ghost">Suspend account</button></div></section><aside className="panel admin-profile-summary"><span className="avatar">AM</span><h3>Alex Morgan</h3><p>Student · Explorer plan</p><dl><div><dt>Quiz status</dt><dd>Completed</dd></div><div><dt>Saved careers</dt><dd>3</dd></div><div><dt>Last active</dt><dd>2 min ago</dd></div><div><dt>Member since</dt><dd>Mar 3, 2026</dd></div></dl></aside></div></div>
}
